// harness/kimi/manifest.ts — the Kimi Code CLI distribution row.
//
// Projects the harness-neutral core/ tree into dist/kimi/.kimi-code/, plus
// Kimi's authored shell surfaces (orchestrator skill + question-rendering
// annex, the managed-block hook snippet, the project-root AGENTS.md and
// .gitignore). Declarative only — no emit() plugin, default runner-gen
// (ADR-2: Kimi tolerates the runner-gen frontmatter, measured 2026-07-25).
//
// Kimi specifics vs Claude/Kiro:
//   - token → .kimi-code (Kimi's project-level detection dir for
//     skills/agents — ADR-1; the legacy `.kimi` path belongs to the retired
//     kimi-cli product)
//   - rulesRename: null — rules/ projects unrenamed (BR-1). The row is inert
//     today (core/rules/ carries no files; the AIDLC method lives at the
//     workspace root under amadeus/spaces/<space>/memory/), declared so a
//     future core/rules/ file lands at .kimi-code/rules/ untranslated.
//   - the orchestrator skill (skills/amadeus/) is authored here, NOT core —
//     only the six session skills come through coreDirs.
//   - hooks are wired OUTSIDE the project tree: Kimi has no project-level
//     config file, so the shipped hooks/amadeus-hooks.snippet.toml is the
//     single source (ADR-4) the setup CLI merges into the user-level
//     ~/.kimi-code/config.toml as a marker-fenced managed block. The Bolt 2
//     adapter it routes to (amadeus-kimi-adapter.ts + amadeus-kimi-lib.ts)
//     now ships via harnessFiles; the authoredExempt below keeps the
//     orphan scan off them.
//   - AGENTS.md lands at the PROJECT ROOT (dist/kimi/AGENTS.md), outside
//     .kimi-code/ (Kimi merges the root AGENTS.md into ambient context).

import type { HarnessManifest } from "../../../../scripts/manifest-types.ts";
import onboardingFills from "./onboarding.fills.ts";

const manifest: HarnessManifest = {
  name: "kimi",
  mirrorSurface: "kimi",
  harnessDir: ".kimi-code",

  // core/<src> → <harnessDir>/<dst>. Same projection as claude (8 dirs,
  // rules→rules with NO rename) + the six harness-neutral session skills
  // (BR-2). Session skills ship via coreDirs; the orchestrator and the
  // stage/scope runners are generated by runner-gen — no double placement.
  coreDirs: [
    { src: "tools", dst: "tools" },
    { src: "amadeus-common", dst: "amadeus-common" },
    { src: "knowledge", dst: "knowledge" },
    { src: "rules", dst: "rules" },
    { src: "sensors", dst: "sensors" },
    { src: "scopes", dst: "scopes" },
    { src: "agents", dst: "agents" },
    { src: "hooks", dst: "hooks" },
    // The six harness-neutral session skills ship in-tree under skills/.
    { src: "skills/amadeus-session-cost", dst: "skills/amadeus-session-cost" },
    { src: "skills/amadeus-replay", dst: "skills/amadeus-replay" },
    { src: "skills/amadeus-outcomes-pack", dst: "skills/amadeus-outcomes-pack" },
    { src: "skills/amadeus-grilling", dst: "skills/amadeus-grilling" },
    { src: "skills/amadeus-mirror", dst: "skills/amadeus-mirror" },
    { src: "skills/amadeus-election", dst: "skills/amadeus-election" },
  ],

  // Authored harness surfaces copied verbatim (with token substitution on
  // .md) from harness/kimi/<src> → <harnessDir>/<dst>. The snippet is .toml,
  // so it copies byte-for-byte. dot-gitignore is the authored name so it does
  // not act as a live ignore inside harness/kimi/; projectRoot routes it to
  // dist/kimi/.gitignore + the --check drift guard (byte-shaped like
  // codex/opencode — the workspace layout is harness-neutral).
  harnessFiles: [
    { src: "skills/amadeus/SKILL.md", dst: "skills/amadeus/SKILL.md" },
    { src: "skills/amadeus/question-rendering.md", dst: "skills/amadeus/question-rendering.md" },
    // The managed-block source of truth (ADR-4): installer merge, doctor
    // inspection, and the docs' manual procedure all read this one snippet.
    { src: "hooks/amadeus-hooks.snippet.toml", dst: "hooks/amadeus-hooks.snippet.toml" },
    // The Bolt 2 hook adapter the snippet routes to: thin shim + logic lib
    // (the cursor-lib split idiom). They land inside the core-copied hooks/
    // dir, so the orphan scan exemption below stays.
    { src: "hooks/amadeus-kimi-adapter.ts", dst: "hooks/amadeus-kimi-adapter.ts" },
    { src: "hooks/amadeus-kimi-lib.ts", dst: "hooks/amadeus-kimi-lib.ts" },
    { src: "dot-gitignore", dst: ".gitignore", projectRoot: true },
  ],

  // AGENTS.md renders from the shared skeleton with Kimi's fills, at the
  // project root (outside .kimi-code/). The {{HARNESS_DIR}} → .kimi-code
  // substitution runs on it like any core .md.
  onboarding: { dst: "AGENTS.md", projectRoot: true, fills: onboardingFills },

  // Kimi renames no core dir (BR-1).
  rulesRename: null,

  // The Bolt 2 hook adapter + lib live inside the core-copied hooks/ dir —
  // exempt the authored amadeus-kimi-*.ts files from the orphan scan (they
  // are harnessFiles, not core-derived).
  authoredExempt: [/^hooks\/amadeus-kimi-[^/]+\.ts$/],

  // No emit() plugin: Kimi's runners come from the shared runner-gen
  // composition and its compiled data from graph compile, both driven by the
  // packager (ADR-2 — the codex-style emit was rejected as unneeded).
  emit: null,
};

export default manifest;
