// covers: function:parseStageFrontmatter, function:emitStageFrontmatter,
//         function:validateStageFrontmatter, function:validateDirective,
//         function:artifactsRegistry,
//         function:producersOf, function:compileStageGraph,
//         subcommand:amadeus-orchestrate:next,
//         subcommand:amadeus-sensor:fire
//
// `optional_produces` names artifacts a per-unit stage may legitimately omit.
// Tests exercise the canonical source interfaces; generated dist trees are
// regenerated by the repository-wide packaging step after this change lands.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  __resetGraphCache,
  artifactsRegistry,
  compileStageGraph,
  producersOf,
} from "../../packages/framework/core/tools/amadeus-graph.ts";
import { validateDirective } from "../../packages/framework/core/tools/amadeus-directive.ts";
import {
  _resetStageGraphForTests,
  emitStageFrontmatter,
  parseStageFrontmatter,
} from "../../packages/framework/core/tools/amadeus-lib.ts";
import { validateStageFrontmatter } from "../../packages/framework/core/tools/amadeus-stage-schema.ts";
import {
  cleanupTestProject,
  createTestProject,
  DEFAULT_RECORD_DIR,
  DEFAULT_SPACE,
  seededRecordDir,
  seededStateFile,
} from "../harness/fixtures.ts";

const REPO_ROOT = join(import.meta.dir, "..", "..");

const WITH_OPTIONAL = `---
slug: functional-design
phase: construction
execution: CONDITIONAL
condition: x
lead_agent: amadeus-architect-agent
support_agents: []
mode: inline
for_each: unit-of-work
produces:
  - business-logic-model
  - business-rules
optional_produces:
  - frontend-components
consumes: []
requires_stage: []
inputs: a
outputs: b
---

# Functional Design
`;

describe("t212 optional_produces frontmatter", () => {
  test("parse and emit preserve the optional artifact list", () => {
    const parsed = parseStageFrontmatter(WITH_OPTIONAL);
    expect(parsed.optional_produces).toEqual(["frontend-components"]);

    const emitted = emitStageFrontmatter(parsed);
    expect(parseStageFrontmatter(emitted)).toEqual(parsed);
    expect(emitted.indexOf("\noptional_produces:")).toBeGreaterThan(
      emitted.indexOf("\nproduces:"),
    );

    expect(validateStageFrontmatter(parsed).valid).toBe(true);
  });

  test("absence stays absent and malformed artifact names are rejected", () => {
    const withoutOptional = parseStageFrontmatter(
      WITH_OPTIONAL.replace(
        "optional_produces:\n  - frontend-components\n",
        "",
      ),
    );
    expect("optional_produces" in withoutOptional).toBe(false);

    const invalid = validateStageFrontmatter({
      ...parseStageFrontmatter(WITH_OPTIONAL),
      optional_produces: ["FrontendComponents"],
    });
    expect(invalid.valid).toBe(false);
    if (invalid.valid) throw new Error("invalid optional artifact was accepted");
    expect(invalid.errors).toContain(
      'optional_produces[0] must be kebab-case, got "FrontendComponents"',
    );
  });

  test("required and optional output lists reject duplicates and overlap", () => {
    const parsed = parseStageFrontmatter(WITH_OPTIONAL);
    const duplicateRequired = validateStageFrontmatter({
      ...parsed,
      produces: ["business-rules", "business-rules"],
    });
    const duplicateOptional = validateStageFrontmatter({
      ...parsed,
      optional_produces: ["frontend-components", "frontend-components"],
    });
    const overlap = validateStageFrontmatter({
      ...parsed,
      optional_produces: ["business-rules"],
    });

    expect(duplicateRequired.valid).toBe(false);
    expect(duplicateOptional.valid).toBe(false);
    expect(overlap.valid).toBe(false);
    if (duplicateRequired.valid || duplicateOptional.valid || overlap.valid) {
      throw new Error("duplicate or overlapping output names were accepted");
    }
    expect(duplicateRequired.errors).toContain(
      'produces contains duplicate artifact "business-rules"',
    );
    expect(duplicateOptional.errors).toContain(
      'optional_produces contains duplicate artifact "frontend-components"',
    );
    expect(overlap.errors).toContain(
      'artifact "business-rules" cannot be both required and optional',
    );
  });
});

describe("t212 optional_produces artifact vocabulary", () => {
  let dir: string;
  const previousGraph = process.env.AMADEUS_STAGE_GRAPH;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "amadeus-t212-graph-"));
    const graphPath = join(dir, "stage-graph.json");
    writeFileSync(
      graphPath,
      `${JSON.stringify([
        {
          slug: "producer",
          number: "1.1",
          name: "Producer",
          phase: "ideation",
          execution: "ALWAYS",
          lead_agent: "orchestrator",
          support_agents: [],
          mode: "inline",
          produces: ["required-artifact"],
          optional_produces: ["conditional-artifact"],
          consumes: [],
          requires_stage: [],
          inputs: "a",
          outputs: "b",
          rules_in_context: [],
          sensors_applicable: [],
        },
      ])}\n`,
      "utf-8",
    );
    process.env.AMADEUS_STAGE_GRAPH = graphPath;
    _resetStageGraphForTests();
    __resetGraphCache();
  });

  afterEach(() => {
    if (previousGraph === undefined) delete process.env.AMADEUS_STAGE_GRAPH;
    else process.env.AMADEUS_STAGE_GRAPH = previousGraph;
    _resetStageGraphForTests();
    __resetGraphCache();
    rmSync(dir, { recursive: true, force: true });
  });

  test("registry and producer lookup include optional artifacts", () => {
    expect(artifactsRegistry().has("conditional-artifact")).toBe(true);
    expect(producersOf("conditional-artifact").map((stage) => stage.slug)).toEqual([
      "producer",
    ]);
  });
});

describe("t212 optional_produces compile carry-through", () => {
  test("the two conditional Construction artifacts compile separately from required outputs", () => {
    const envKeys = [
      "AMADEUS_STAGE_GRAPH",
      "AMADEUS_SCOPE_GRID",
      "AMADEUS_STAGES_DIR",
      "AMADEUS_RULES_DIR",
      "AMADEUS_SENSORS_DIR",
    ] as const;
    const previous = Object.fromEntries(
      envKeys.map((key) => [key, process.env[key]]),
    );
    process.env.AMADEUS_STAGE_GRAPH = join(
      REPO_ROOT,
      "dist/claude/.claude/tools/data/stage-graph.json",
    );
    process.env.AMADEUS_SCOPE_GRID = join(
      REPO_ROOT,
      "dist/claude/.claude/tools/data/scope-grid.json",
    );
    process.env.AMADEUS_STAGES_DIR = join(
      REPO_ROOT,
      "packages/framework/core/amadeus-common/stages",
    );
    process.env.AMADEUS_RULES_DIR = join(
      REPO_ROOT,
      "amadeus/spaces/default/memory",
    );
    process.env.AMADEUS_SENSORS_DIR = join(
      REPO_ROOT,
      "packages/framework/core/sensors",
    );

    try {
      _resetStageGraphForTests();
      __resetGraphCache();
      const graph = compileStageGraph().stages;
      const functional = graph.find((stage) => stage.slug === "functional-design");
      const infrastructure = graph.find(
        (stage) => stage.slug === "infrastructure-design",
      );

      expect(functional?.optional_produces).toEqual(["frontend-components"]);
      expect(functional?.produces).not.toContain("frontend-components");
      expect(infrastructure?.optional_produces).toEqual([
        "shared-infrastructure",
      ]);
      expect(infrastructure?.produces).not.toContain("shared-infrastructure");
      expect(
        graph
          .filter((stage) => stage.optional_produces !== undefined)
          .map((stage) => stage.slug),
      ).toEqual(["functional-design", "infrastructure-design"]);
    } finally {
      for (const key of envKeys) {
        const value = previous[key];
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
      }
      _resetStageGraphForTests();
      __resetGraphCache();
    }
  });

  test("compile rejects a producer collision across required and optional output lists", () => {
    const dir = mkdtempSync(join(tmpdir(), "amadeus-t212-collision-"));
    const stages = join(dir, "stages", "ideation");
    const rules = join(dir, "rules");
    const sensors = join(dir, "sensors");
    const graphPath = join(dir, "stage-graph.json");
    const gridPath = join(dir, "scope-grid.json");
    mkdirSync(stages, { recursive: true });
    mkdirSync(rules);
    mkdirSync(sensors);
    writeFileSync(graphPath, "[]\n", "utf-8");

    const stage = (
      slug: string,
      produces: string[],
      optionalProduces: string[],
    ): string => `---
slug: ${slug}
phase: ideation
execution: ALWAYS
condition: fixture
lead_agent: orchestrator
support_agents: []
mode: inline
produces:${produces.length === 0 ? " []" : `\n${produces.map((name) => `  - ${name}`).join("\n")}`}
${optionalProduces.length === 0 ? "" : `optional_produces:\n${optionalProduces.map((name) => `  - ${name}`).join("\n")}\n`}consumes: []
requires_stage: []
inputs: fixture
outputs: fixture
---

# ${slug}
`;
    writeFileSync(
      join(stages, "required-producer.md"),
      stage("required-producer", ["shared-artifact"], []),
      "utf-8",
    );
    writeFileSync(
      join(stages, "optional-producer.md"),
      stage("optional-producer", [], ["shared-artifact"]),
      "utf-8",
    );

    const envKeys = [
      "AMADEUS_STAGE_GRAPH",
      "AMADEUS_SCOPE_GRID",
      "AMADEUS_STAGES_DIR",
      "AMADEUS_RULES_DIR",
      "AMADEUS_SENSORS_DIR",
    ] as const;
    const previous = Object.fromEntries(
      envKeys.map((key) => [key, process.env[key]]),
    );
    process.env.AMADEUS_STAGE_GRAPH = graphPath;
    process.env.AMADEUS_SCOPE_GRID = gridPath;
    process.env.AMADEUS_STAGES_DIR = join(dir, "stages");
    process.env.AMADEUS_RULES_DIR = rules;
    process.env.AMADEUS_SENSORS_DIR = sensors;

    try {
      _resetStageGraphForTests();
      __resetGraphCache();
      expect(() => compileStageGraph()).toThrow(
        /artifact producer collision.*shared-artifact.*optional-producer.*required-producer/i,
      );
    } finally {
      for (const key of envKeys) {
        const value = previous[key];
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
      }
      _resetStageGraphForTests();
      __resetGraphCache();
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("t212 optional_produces per-unit routing and coverage", () => {
  const projects: string[] = [];
  const scratch: string[] = [];
  const orchestrator = join(
    REPO_ROOT,
    "packages/framework/core/tools/amadeus-orchestrate.ts",
  );
  const sensorDispatcher = join(
    REPO_ROOT,
    "packages/framework/core/tools/amadeus-sensor.ts",
  );
  const scopeGrid = join(
    REPO_ROOT,
    "dist/claude/.claude/tools/data/scope-grid.json",
  );

  afterEach(() => {
    while (projects.length > 0) cleanupTestProject(projects.pop());
    while (scratch.length > 0) {
      rmSync(scratch.pop()!, { recursive: true, force: true });
    }
  });

  function sourceGraph(): string {
    const dir = mkdtempSync(join(tmpdir(), "amadeus-t212-runtime-graph-"));
    scratch.push(dir);
    const graph = JSON.parse(
      readFileSync(
        join(REPO_ROOT, "dist/claude/.claude/tools/data/stage-graph.json"),
        "utf-8",
      ),
    ) as Array<Record<string, unknown>>;
    const functional = graph.find(
      (stage) => stage.slug === "functional-design",
    );
    if (!functional || !Array.isArray(functional.produces)) {
      throw new Error("functional-design fixture node missing");
    }
    functional.produces = functional.produces.filter(
      (name) => name !== "frontend-components",
    );
    functional.optional_produces = ["frontend-components"];
    const graphPath = join(dir, "stage-graph.json");
    writeFileSync(graphPath, `${JSON.stringify(graph, null, 2)}\n`, "utf-8");
    return graphPath;
  }

  function isolatedEnv(
    graphPath: string,
    extra: NodeJS.ProcessEnv = {},
  ): NodeJS.ProcessEnv {
    const env: NodeJS.ProcessEnv = {
      ...process.env,
      AMADEUS_STAGE_GRAPH: graphPath,
      AMADEUS_SCOPE_GRID: scopeGrid,
      ...extra,
    };
    delete env.AMADEUS_DEFAULT_SCOPE;
    return env;
  }

  function seedProject(): string {
    const project = createTestProject();
    projects.push(project);
    writeFileSync(
      seededStateFile(project),
      `# AI-DLC State Tracking

## Project Information
- **Project**: optional produces test
- **Project Type**: Greenfield
- **Scope**: feature
- **State Version**: 7
- **Skeleton Stance**: on

## Scope Configuration
- **Stages to Execute**: all
- **Stages to Skip**: none
- **Depth**: Standard
- **Test Strategy**: Standard

## Stage Progress

### CONSTRUCTION PHASE
- [-] functional-design — EXECUTE
- [ ] nfr-requirements — EXECUTE
- [ ] nfr-design — EXECUTE
- [ ] infrastructure-design — EXECUTE
- [ ] code-generation — EXECUTE
- [ ] build-and-test — EXECUTE

### INCEPTION PHASE
- [x] application-design — EXECUTE

## Current Status
- **Lifecycle Phase**: CONSTRUCTION
- **Current Stage**: functional-design
- **Status**: Running
`,
      "utf-8",
    );
    writeFileSync(
      join(seededRecordDir(project), "runtime-graph.json"),
      `${JSON.stringify(
        {
          bolt_dag: {
            units: [
              { name: "alpha", depends_on: [] },
              { name: "beta", depends_on: [] },
            ],
            batches: [["alpha", "beta"]],
          },
        },
        null,
        2,
      )}\n`,
      "utf-8",
    );
    return project;
  }

  function coverRequired(project: string, unit: string): void {
    const dir = join(
      seededRecordDir(project),
      "construction",
      unit,
      "functional-design",
    );
    mkdirSync(dir, { recursive: true });
    for (const artifact of [
      "business-logic-model",
      "business-rules",
      "domain-entities",
    ]) {
      writeFileSync(join(dir, `${artifact}.md`), `# ${artifact}\n`, "utf-8");
    }
  }

  function coverArtifacts(
    project: string,
    unit: string,
    artifacts: string[],
  ): void {
    const dir = join(
      seededRecordDir(project),
      "construction",
      unit,
      "functional-design",
    );
    mkdirSync(dir, { recursive: true });
    for (const artifact of artifacts) {
      writeFileSync(join(dir, `${artifact}.md`), `# ${artifact}\n`, "utf-8");
    }
  }

  test("required-only coverage advances while the directive still routes the optional artifact", () => {
    const project = seedProject();
    coverRequired(project, "alpha");
    const result = spawnSync(
      process.execPath,
      [orchestrator, "next", "--project-dir", project],
      {
        encoding: "utf-8",
        env: isolatedEnv(sourceGraph(), {
          AMADEUS_SKIP_ARTIFACT_GUARD: "1",
          AMADEUS_SKIP_HUMAN_PRESENCE_GUARD: "1",
        }),
      },
    );
    expect(result.status).toBe(0);
    const directive = JSON.parse(result.stdout.trim()) as {
      kind: string;
      unit?: string;
      produces?: string[];
      optional_produces?: string[];
    };
    const optionalPath =
      `amadeus/spaces/${DEFAULT_SPACE}/intents/${DEFAULT_RECORD_DIR}` +
      "/construction/beta/functional-design/frontend-components.md";
    expect(directive.kind).toBe("run-stage");
    expect(directive.unit).toBe("beta");
    expect(directive.produces).toContain(optionalPath);
    expect(directive.optional_produces).toEqual([optionalPath]);
    expect(validateDirective(directive).valid).toBe(true);

    const dispatchDirective = {
      ...directive,
      kind: "dispatch-subagent",
      worker: "amadeus-architect-agent",
    };
    expect(validateDirective(dispatchDirective).valid).toBe(true);

    expect(
      validateDirective({ ...directive, optional_produces: optionalPath }).valid,
    ).toBe(false);

    const duplicateProduces = validateDirective({
      ...directive,
      produces: [...(directive.produces ?? []), optionalPath],
    });
    const duplicateOptional = validateDirective({
      ...directive,
      optional_produces: [optionalPath, optionalPath],
    });
    const unrelatedPath = optionalPath.replace(
      "frontend-components.md",
      "unrelated.md",
    );
    const nonSubset = validateDirective({
      ...dispatchDirective,
      optional_produces: [unrelatedPath],
    });

    expect(duplicateProduces.valid).toBe(false);
    expect(duplicateOptional.valid).toBe(false);
    expect(nonSubset.valid).toBe(false);
    if (duplicateProduces.valid || duplicateOptional.valid || nonSubset.valid) {
      throw new Error("malformed output candidate contract was accepted");
    }
    expect(duplicateProduces.errors).toContain(
      `run-stage: produces contains duplicate path "${optionalPath}"`,
    );
    expect(duplicateOptional.errors).toContain(
      `run-stage: optional_produces contains duplicate path "${optionalPath}"`,
    );
    expect(nonSubset.errors).toContain(
      `dispatch-subagent: optional_produces path "${unrelatedPath}" must also appear in produces`,
    );
  }, 30_000);

  test("an optional artifact cannot replace a missing required artifact", () => {
    const project = seedProject();
    coverArtifacts(project, "alpha", [
      "business-logic-model",
      "business-rules",
      "frontend-components",
    ]);
    const result = spawnSync(
      process.execPath,
      [orchestrator, "next", "--project-dir", project],
      {
        encoding: "utf-8",
        env: isolatedEnv(sourceGraph(), {
          AMADEUS_SKIP_ARTIFACT_GUARD: "1",
          AMADEUS_SKIP_HUMAN_PRESENCE_GUARD: "1",
        }),
      },
    );
    expect(result.status).toBe(0);
    const directive = JSON.parse(result.stdout.trim()) as {
      kind: string;
      unit?: string;
    };
    expect(directive.kind).toBe("run-stage");
    expect(directive.unit).toBe("alpha");
  }, 30_000);

  test("required-sections receives optional artifacts in its template-eligible set", () => {
    const project = seedProject();
    const dir = mkdtempSync(join(tmpdir(), "amadeus-t212-sensor-"));
    scratch.push(dir);
    const manifests = join(dir, "manifests");
    const scripts = join(dir, "scripts");
    mkdirSync(manifests);
    mkdirSync(scripts);
    const capturePath = join(dir, "args.json");
    const outputPath = join(project, "frontend-components.md");
    writeFileSync(outputPath, "# Frontend\n\n## Components\n\n## Notes\n", "utf-8");
    writeFileSync(
      join(manifests, "amadeus-required-sections.md"),
      `---
id: required-sections
kind: deterministic
command: bun .claude/tools/capture-args.ts
default_severity: advisory
description: optional produces argument capture
---
# Capture
`,
      "utf-8",
    );
    writeFileSync(
      join(scripts, "capture-args.ts"),
      `import { writeFileSync } from "node:fs";
const output = process.env.AMADEUS_T212_CAPTURE;
if (!output) throw new Error("AMADEUS_T212_CAPTURE is required");
writeFileSync(output, JSON.stringify(process.argv.slice(2)), "utf-8");
console.log(JSON.stringify({ pass: true }));
`,
      "utf-8",
    );

    const result = spawnSync(
      process.execPath,
      [
        sensorDispatcher,
        "fire",
        "required-sections",
        "--stage",
        "functional-design",
        "--output-path",
        outputPath,
        "--project-dir",
        project,
      ],
      {
        encoding: "utf-8",
        env: isolatedEnv(sourceGraph(), {
          AMADEUS_SENSORS_DIR: manifests,
          AMADEUS_SENSOR_SCRIPT_DIR: scripts,
          AMADEUS_T212_CAPTURE: capturePath,
        }),
      },
    );

    expect(result.status).toBe(0);
    const args = JSON.parse(readFileSync(capturePath, "utf-8")) as string[];
    const eligibleIndex = args.indexOf("--template-eligible");
    expect(eligibleIndex).toBeGreaterThan(-1);
    expect(args[eligibleIndex + 1]?.split(",")).toContain(
      "frontend-components",
    );
  }, 30_000);
});
