// covers: file:packages/framework/core/tools/amadeus-orchestrate.ts, file:packages/framework/core/tools/amadeus-intent-autonomy-production.ts, subcommand:amadeus-orchestrate:report, subcommand:amadeus-orchestrate:next
// size: medium

import { afterEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { appendFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { cleanupTestProject, setupIntegrationProject } from "../harness/fixtures.ts";
import { resetOtelPerProject } from "../harness/otel-reset.ts";
// The engine reads its compiled stage graph out of the tools tree it lives in,
// so both halves are driven through the shipped copy (t213 / t-batch3 precedent):
// a stale dist reds here instead of passing against un-regenerated bytes.
import {
  applyProductionAutonomyMode,
  previewProductionAutonomyGrant,
  readProductionAutonomyProjection,
} from "../../dist/claude/.claude/tools/amadeus-intent-autonomy-production.ts";
import {
  handleNext,
  handleReport,
  stageFailureDirective,
} from "../../dist/claude/.claude/tools/amadeus-orchestrate.ts";

class ExitSignal extends Error {}

function capture(fn: () => void): string {
  let stdout = "";
  const origExit = process.exit.bind(process);
  const origLog = console.log;
  const origErr = console.error;
  process.exit = ((code?: number) => {
    throw new ExitSignal(String(code ?? 0));
  }) as typeof process.exit;
  console.log = (...a: unknown[]) => {
    stdout += `${a.map(String).join(" ")}\n`;
  };
  console.error = () => {};
  try {
    fn();
  } catch (e) {
    if (!(e instanceof ExitSignal)) throw e;
  } finally {
    process.exit = origExit;
    console.log = origLog;
    console.error = origErr;
  }
  return stdout;
}

function directive(stdout: string): Record<string, unknown> {
  const line = stdout.split("\n").filter((row) => row.trim().startsWith("{")).at(-1);
  if (line === undefined) throw new Error(`no directive in output: ${stdout}`);
  return JSON.parse(line) as Record<string, unknown>;
}

function recordDir(projectDir: string): string {
  const intents = join(projectDir, "amadeus", "spaces", "default", "intents");
  return join(intents, readFileSync(join(intents, "active-intent"), "utf8").trim());
}

function appendHumanTurn(projectDir: string): void {
  const auditDir = join(recordDir(projectDir), "audit");
  mkdirSync(auditDir, { recursive: true });
  const path = join(auditDir, "referee-failure-test.jsonl");
  const seq = existsSync(path)
    ? readFileSync(path, "utf8").split("\n").filter(Boolean).length + 1
    : 1;
  appendFileSync(path, `${JSON.stringify({
    schemaVersion: 1,
    seq,
    cloneId: "referee-failure-test",
    intentId: "referee-failure-test",
    timestamp: new Date().toISOString(),
    heading: "Human Turn",
    event: "HUMAN_TURN",
    fields: {},
  })}\n`);
}

function bornProject(): string {
  const projectDir = setupIntegrationProject({ noAidlcDocs: true, stripEnvScope: true });
  const born = spawnSync(
    process.execPath,
    [
      join(projectDir, ".claude", "tools", "amadeus-utility.ts"),
      "intent-birth",
      "--scope",
      "feature",
      "--project-dir",
      projectDir,
    ],
    { cwd: projectDir, encoding: "utf8", env: { ...process.env } },
  );
  expect(born.status).toBe(0);
  return projectDir;
}

function grantFullAutonomy(projectDir: string): void {
  appendHumanTurn(projectDir);
  const stateContent = readFileSync(join(recordDir(projectDir), "amadeus-state.md"), "utf8");
  const preview = previewProductionAutonomyGrant({ projectDir, stateContent });
  expect(preview.ok).toBe(true);
  if (!preview.ok) return;
  expect(applyProductionAutonomyMode({
    projectDir,
    stateContent,
    mode: "full",
    confirmedDisplayDigest: preview.preview.displayDigest,
  })).toMatchObject({ ok: true, projection: { mode: "full" } });
}

const FAILURE = '{"ok":false,"failure":{"kind":"invalid-grammar","tokens":["FR-2"]}}';

function reportRefereeFailure(projectDir: string): Record<string, unknown> {
  return directive(capture(() => handleReport(
    ["--stage", "code-generation", "--result", "failed", "--failure", FAILURE],
    projectDir,
  )));
}

let projectDir = "";
afterEach(() => {
  resetOtelPerProject();
  if (projectDir) cleanupTestProject(projectDir);
  projectDir = "";
});

describe("full autonomy typed referee failure", () => {
  test("admits the failure into bounded repair and parks as REPAIR_STALLED", () => {
    projectDir = bornProject();
    grantFullAutonomy(projectDir);

    const outcomes = Array.from({ length: 7 }, () => reportRefereeFailure(projectDir));
    // Bounded repair owns the recovery: repeated repair rounds, one replan, then
    // the stall. No round may fall back to the forward-only report error.
    expect(outcomes.map((row) => row.kind)).toEqual([
      "print", "print", "print", "print", "print", "print", "parked",
    ]);
    expect(String(outcomes[0]!.message)).toContain("repair");
    expect(String(outcomes[3]!.message)).toContain("replan");
    expect(String(outcomes[6]!.reason)).toContain("REPAIR_STALLED");

    const projection = readProductionAutonomyProjection(projectDir);
    expect(projection).toMatchObject({
      mode: "full",
      workflowExecutionState: "suspended",
      parkEnvelope: { reason: "REPAIR_STALLED", resumeCondition: { kind: "quality-evidence-or-human" } },
    });
    // The full grant survives the stall — this is a safe stop, not a downgrade.
    expect(projection?.currentGrant?.state).toBe("active");

    // The infinite re-issue this fixes: `next` must surface the stall instead of
    // re-emitting the same run-stage directive.
    const advanced = directive(capture(() => handleNext([], projectDir)));
    expect(advanced.kind).toBe("parked");
    expect(String(advanced.reason)).toContain("REPAIR_STALLED");
    expect(String(advanced.reason)).toContain("resume-quality");
  });

  test("refuses an admission it cannot ground", () => {
    projectDir = bornProject();
    grantFullAutonomy(projectDir);

    const noDetail = directive(capture(() => handleReport(
      ["--stage", "code-generation", "--result", "failed"],
      projectDir,
    )));
    expect(noDetail.kind).toBe("error");
    expect(String(noDetail.message)).toContain("--failure <detail>");

    // A slug the graph does not carry would open a quality scope nothing resumes.
    const badStage = directive(capture(() => handleReport(
      ["--stage", "not a stage id", "--result", "failed", "--failure", FAILURE],
      projectDir,
    )));
    expect(badStage.kind).toBe("error");
    expect(String(badStage.message)).toContain("unknown stage");
  });

  test("refuses to name a move when Quality Repair could not take the failure", () => {
    // Production reaches this only when the Intent stops being admissible between
    // the mode read and the admission; the refusal itself is a pure mapping.
    expect(stageFailureDirective("code-generation", {
      kind: "error",
      reason: "active-intent-required",
    })).toEqual({
      kind: "error",
      message: 'Cannot admit the failure of stage "code-generation": active-intent-required.',
    });
  });

  test("keeps the forward-only report contract when autonomy is not granted", () => {
    projectDir = bornProject();
    const result = reportRefereeFailure(projectDir);
    expect(result.kind).toBe("error");
    expect(String(result.message)).toContain("forward transitions only");
    expect(readProductionAutonomyProjection(projectDir)?.workflowExecutionState).toBe("running");
    expect(directive(capture(() => handleNext([], projectDir))).kind).not.toBe("parked");
  });
});
