// hermetic-git-env.ts — #3413: keep every git subprocess a test spawns bound
// to the fixture it names, never to the repository the test run itself lives in.
//
// THE LEAK. git exports GIT_DIR into hook processes started from a LINKED
// WORKTREE (measured on git 2.55: a pre-commit hook in a linked worktree sees
// GIT_DIR=<repo>/.git/worktrees/<name>; the same hook in the main checkout does
// not). lefthook inherits that environment and hands it down the chain
// `bun scripts/precommit-related-unit-tests.ts` -> `tests/run-tests.ts` ->
// `bun test <file>` -> the fixture's own `spawnSync("git", ...)`.
//
// THE BINDING OUTRANKS BOTH `cwd:` AND `-C <dir>`. A fixture that does
// everything right — every invocation carries an explicit scratch directory —
// still reaches the real repository. Two INDEPENDENT vectors, both measured:
//   GIT_DIR        `git -C <scratch> config user.email t@t` writes the REAL
//                  shared config; `git -C <scratch> init --bare` sets
//                  core.bare=true on it; `git remote add` / `git push -u` add
//                  the fixture's origin and branch to it.
//   GIT_INDEX_FILE survives removing GIT_DIR: `git -C <scratch> add <file>`
//                  then stages into the REAL index, so an in-flight commit
//                  records a tree from a directory it never touched.
// That composite is exactly the #3413 damage report. No amount of per-fixture
// cwd discipline can fix it, because cwd is not what git resolves first, and
// pinning GIT_CONFIG_* cannot fix it either — the damage lands in the
// repository-LOCAL config, which no global/system pin covers. Deleting the
// binding variables is the fix; the config pinning below is auxiliary
// hardening against host state.
//
// WHAT THIS MODULE IS. The single definition of "an environment no git call can
// use to reach outside its own fixture": the ambient-binding variables to
// remove, and the pinned global/system config that replaces whatever the host
// machine or CI runner happens to carry. `tests/run-tests.ts` applies it to its
// own process environment (so every per-file `bun test` spawn and every tool
// spawn inherits it), and `scripts/precommit-related-unit-tests.ts` applies it
// to the runner spawn it starts from inside the hook.
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** Every environment variable through which git can bind a command to a
 *  repository OTHER than the one its `cwd`/`-C` names, plus the identity and
 *  one-shot-config channels a hook run leaks into its children. Removing these
 *  does not disable git — it only forces discovery to fall back to the working
 *  directory the caller actually asked for. GIT_EXEC_PATH and PATH are
 *  deliberately absent: they locate git itself, not a repository. */
export const AMBIENT_GIT_BINDING_VARS = [
  "GIT_DIR",
  "GIT_WORK_TREE",
  "GIT_COMMON_DIR",
  "GIT_INDEX_FILE",
  "GIT_OBJECT_DIRECTORY",
  "GIT_ALTERNATE_OBJECT_DIRECTORIES",
  "GIT_NAMESPACE",
  "GIT_GRAFT_FILE",
  "GIT_PREFIX",
  "GIT_CONFIG_PARAMETERS",
  "GIT_CONFIG_COUNT",
  // Not a repository binding, but it decides whether the GIT_CONFIG_SYSTEM pin
  // below is read at all: with GIT_CONFIG_NOSYSTEM=1 still in the environment,
  // git skips system config entirely and the pin silently stops applying
  // (measured on git 2.55: `git config --get` of a key present only in the
  // pinned system file returns nothing, exit 1, while the global pin still
  // resolves). Leaving it would put part of the config resolution outside this
  // module's control.
  "GIT_CONFIG_NOSYSTEM",
  "GIT_AUTHOR_NAME",
  "GIT_AUTHOR_EMAIL",
  "GIT_AUTHOR_DATE",
  "GIT_COMMITTER_NAME",
  "GIT_COMMITTER_EMAIL",
  "GIT_COMMITTER_DATE",
] as const;

/** The pinned global config every test-spawned git call reads instead of the
 *  developer's ~/.gitconfig. It is not empty on purpose:
 *  - `user.*` gives fixtures that commit without `-c` an identity, which a bare
 *    CI runner does not otherwise have.
 *  - `safe.directory = *` replaces the entry actions/checkout writes into the
 *    runner's real global config, which pinning would otherwise hide.
 *  - `init.defaultBranch` removes git's advice noise from fixture output.
 *  - gpg signing off: a signing key configured on a contributor's machine must
 *    never be invoked (or block on a passphrase) inside a test. */
export const HERMETIC_GLOBAL_GITCONFIG = [
  "# Generated by tests/lib/hermetic-git-env.ts (#3413). Do not edit.",
  "[user]",
  "\tname = Amadeus Test",
  "\temail = amadeus-test@example.invalid",
  "[init]",
  "\tdefaultBranch = main",
  "[safe]",
  "\tdirectory = *",
  "[commit]",
  "\tgpgsign = false",
  "[tag]",
  "\tgpgsign = false",
  "",
].join("\n");

/** The system config is pinned to a file that declares nothing: /etc/gitconfig
 *  is host state a test must not depend on. */
export const HERMETIC_SYSTEM_GITCONFIG = [
  "# Generated by tests/lib/hermetic-git-env.ts (#3413). Do not edit.",
  "",
].join("\n");

export interface HermeticGitConfigPaths {
  readonly global: string;
  readonly system: string;
}

function writeIfStale(path: string, content: string): void {
  try {
    if (readFileSync(path, "utf-8") === content) return;
  } catch {
    // Missing or unreadable: fall through and (re)write it.
  }
  // Write-then-rename so a concurrent runner never observes a half-written
  // config; the two runners write identical bytes, so either winner is correct.
  const staging = `${path}.${process.pid}.tmp`;
  writeFileSync(staging, content, "utf-8");
  renameSync(staging, path);
}

/** Materialise the pinned global/system config on disk and return their paths.
 *  The location is stable (not a fresh mkdtemp) so repeated runs reuse one pair
 *  of files instead of accumulating temp directories. */
export function materializeHermeticGitConfig(
  dir: string = join(process.env.TMPDIR || tmpdir(), "amadeus-hermetic-git"),
): HermeticGitConfigPaths {
  mkdirSync(dir, { recursive: true });
  const paths: HermeticGitConfigPaths = {
    global: join(dir, "global.gitconfig"),
    system: join(dir, "system.gitconfig"),
  };
  writeIfStale(paths.global, HERMETIC_GLOBAL_GITCONFIG);
  writeIfStale(paths.system, HERMETIC_SYSTEM_GITCONFIG);
  return paths;
}

/** Strip the ambient repository binding from `env` in place and pin the git
 *  config files. Used on `process.env`, where every later spawn inherits it. */
export function applyHermeticGitEnv(
  env: NodeJS.ProcessEnv,
  config: HermeticGitConfigPaths,
): void {
  for (const name of AMBIENT_GIT_BINDING_VARS) delete env[name];
  env.GIT_CONFIG_GLOBAL = config.global;
  env.GIT_CONFIG_SYSTEM = config.system;
}

/** The pure form: a copy of `base` with the ambient binding removed and the
 *  config pinned. `base` is not mutated. */
export function hermeticGitEnv(
  base: NodeJS.ProcessEnv,
  config: HermeticGitConfigPaths,
): NodeJS.ProcessEnv {
  const copy: NodeJS.ProcessEnv = { ...base };
  applyHermeticGitEnv(copy, config);
  return copy;
}
