// In-process coverage seam for the #789 advance-direction guard (FR-5). The
// spawn-driven integration test drives the same contract end-to-end through the
// shipped dist CLI, which bun's coverage instrumentation cannot see (the spawn
// blindspot). So this unit test imports the pure helper directly and drives all
// three branches in-process: forward (ok), backward (reject), same-position
// (reject). Behavioural depth stays in the integration test; this file exists so
// the added lines register in lcov (local-lcov-pre-push).
//
// Imported from dist/claude (the shipped tree) per the #761 seam precedent, so a
// stale dist reds here rather than passing against un-regenerated bytes.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import {
  advanceDirectionCheck,
  handleAdvance,
} from "../../dist/claude/.claude/tools/amadeus-state.ts";
import {
  cleanupTestProject,
  createTestProject,
  seedStateFile,
} from "../harness/fixtures.ts";

describe("t-advance-direction-seam: advanceDirectionCheck (FR-5)", () => {
  test("next after completed → ok (forward)", () => {
    expect(advanceDirectionCheck(10, 11)).toEqual({ ok: true });
  });

  test("next before completed → reject (backward)", () => {
    // The #789 repro shape: a 2-arg advance naming a past slug. Without the
    // guard this regressed Current Stage and minted a forward-form PHASE_*.
    const r = advanceDirectionCheck(11, 3);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toContain("jump");
  });

  test("next equals completed → reject (same position)", () => {
    const r = advanceDirectionCheck(7, 7);
    expect(r.ok).toBe(false);
  });
});

// In-process drive of handleAdvance itself — the pure-helper cases cover the
// direction math, but the handler body that CALLS it (the index derivation and
// the loud-reject error path inside the audit-lock critical section) is only
// reachable through the CLI, which the spawn-driven t17 case cannot register in
// lcov. The state seed is required so readStateFile / emitError resolve the
// active intent (inprocess-fixture-state-seed).

class ExitSignal extends Error {
  constructor(public readonly code: number) {
    super(`exit ${code}`);
  }
}

// error() ends the CLI via process.exit and writes the message via console.error;
// in-process we convert the exit into a throwable and capture stderr.
function captureExit(fn: () => void): { threw: boolean; stderr: string } {
  let stderr = "";
  const origExit = process.exit.bind(process);
  const origErr = console.error;
  process.exit = ((code?: number) => {
    throw new ExitSignal(code ?? 0);
  }) as typeof process.exit;
  console.error = (...a: unknown[]) => {
    stderr += a.map(String).join(" ");
  };
  let threw = false;
  try {
    fn();
  } catch (e) {
    if (e instanceof ExitSignal) threw = true;
    else throw e;
  } finally {
    process.exit = origExit;
    console.error = origErr;
  }
  return { threw, stderr };
}

describe("t-advance-direction-seam: handleAdvance drive (FR-5, in-process)", () => {
  let proj: string;
  let prevProjectDir: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    seedStateFile(proj, "state-construction-bolt1.md");
    prevProjectDir = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prevProjectDir === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prevProjectDir;
    cleanupTestProject(proj);
  });

  test("2-arg advance to a past stage is rejected loudly, before any emit", () => {
    // Current Stage is functional-design (construction); naming requirements-
    // analysis (inception) as <next> is a backward 2-arg advance → the guard
    // rejects it. The single-arg form always derives forward, so only this
    // caller-supplied backward slug reaches the check.
    const r = captureExit(() =>
      handleAdvance(["functional-design", "requirements-analysis"]),
    );
    expect(r.threw).toBe(true);
    expect(r.stderr).toContain("Cannot advance");
    expect(r.stderr).toContain("jump");
  });
});
