// In-process coverage seam for core-repair batch3 U6 (#744 / #749).
//
// The behavioural depth lives in the spawn-driven integration tests (t179 for
// the FR-10 latch case; the phase / single cases exercise the shipped dist CLI
// end-to-end), which bun's coverage instrumentation cannot see through the
// spawn (the spawn blindspot). So this file imports the pure helpers directly
// and drives both branches in-process, so the added lines register in lcov
// (local-lcov-pre-push).
//
// The helpers are imported from dist/claude (the shipped tree), matching the
// #761 / t-jump-direction-seam precedent — a stale dist reds here rather than
// passing against un-regenerated bytes.
//
// #744: ownPhase gates PHASE_NUMBERS lookups on own-property membership, so the
//       all-lowercase Object.prototype members (`constructor`, `__proto__`) that
//       a bare index would surface fall on the null path. Three copies (one per
//       tool) are asserted identical here.
// #749: resolveSingleGate rewrites a --single run's GATE_UNRESOLVED to a
//       determinate gated boolean (the classify round-trip does not exist for a
//       standalone single run), leaving every already-determinate gate untouched.

import { describe, expect, test } from "bun:test";
import { ownPhase as ownPhaseOrchestrate, resolveSingleGate } from "../../dist/claude/.claude/tools/amadeus-orchestrate.ts";
import { ownPhase as ownPhaseJump } from "../../dist/claude/.claude/tools/amadeus-jump.ts";
import { ownPhase as ownPhaseState } from "../../dist/claude/.claude/tools/amadeus-state.ts";

const copies: Array<[string, (input: string) => string | null]> = [
  ["orchestrate", ownPhaseOrchestrate],
  ["jump", ownPhaseJump],
  ["state", ownPhaseState],
];

describe("t-batch3 seam: ownPhase own-key guard (#744)", () => {
  for (const [name, ownPhase] of copies) {
    describe(name, () => {
      test("prototype-chain members resolve to null", () => {
        // The two all-lowercase Object.prototype members a bare index leaks.
        expect(ownPhase("constructor")).toBeNull();
        expect(ownPhase("__proto__")).toBeNull();
      });

      test("own name keys canonicalise unchanged", () => {
        expect(ownPhase("construction")).toBe("construction");
        expect(ownPhase("Ideation")).toBe("ideation");
        expect(ownPhase("OPERATION")).toBe("operation");
      });

      test("own number keys canonicalise to their phase name", () => {
        expect(ownPhase("0")).toBe("initialization");
        expect(ownPhase("3")).toBe("construction");
      });

      test("unknown tokens resolve to null", () => {
        expect(ownPhase("bogus")).toBeNull();
        expect(ownPhase("hasownproperty")).toBeNull();
      });
    });
  }
});

describe("t-batch3 seam: resolveSingleGate (#749)", () => {
  test("unresolved becomes a determinate gated boolean", () => {
    expect(resolveSingleGate("unresolved")).toBe(true);
  });

  test("already-determinate gates pass through untouched", () => {
    expect(resolveSingleGate(true)).toBe(true);
    expect(resolveSingleGate(false)).toBe(false);
  });
});
