// In-process coverage seam for the #787 jump-direction reconciliation (FR-4).
// The spawn-driven integration test (t19 / the new t-jump-direction-guard case)
// exercises the same contract end-to-end through the shipped dist CLI, which
// bun's coverage instrumentation cannot see (the spawn blindspot). So this unit
// test imports the pure helpers directly and drives both branches in-process:
// the direction derivation (forward / backward / redo) and the reconcile
// success / mismatch paths. Behavioural depth stays in the integration test;
// this file exists so the added lines register in lcov (local-lcov-pre-push).
//
// The helpers are imported from dist/claude (the shipped tree), matching the
// #761 seam precedent — so a stale dist reds here rather than passing against
// un-regenerated bytes.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import {
  deriveDirection,
  directionReconcile,
  handleExecute,
  handleResolve,
} from "../../dist/claude/.claude/tools/amadeus-jump.ts";
import {
  cleanupTestProject,
  createTestProject,
  seedStateFile,
} from "../harness/fixtures.ts";

describe("t-jump-direction-seam: deriveDirection (FR-4)", () => {
  test("target after current → forward", () => {
    expect(deriveDirection(2, 5)).toBe("forward");
  });

  test("target before current → backward", () => {
    expect(deriveDirection(5, 2)).toBe("backward");
  });

  test("target equals current → redo", () => {
    expect(deriveDirection(4, 4)).toBe("redo");
  });
});

describe("t-jump-direction-seam: directionReconcile (FR-4)", () => {
  test("supplied matches derived forward → ok", () => {
    expect(directionReconcile("forward", 2, 5)).toEqual({ ok: true });
  });

  test("supplied matches derived backward → ok", () => {
    expect(directionReconcile("backward", 5, 2)).toEqual({ ok: true });
  });

  test("supplied matches derived redo → ok", () => {
    expect(directionReconcile("redo", 4, 4)).toEqual({ ok: true });
  });

  test("supplied 'forward' but transition is backward → reject with expected 'backward'", () => {
    // The #787 repro shape: a mis-specified forward to an earlier stage. Without
    // reconciliation this ran the forward branch and regressed Current Stage.
    expect(directionReconcile("forward", 5, 2)).toEqual({
      ok: false,
      expected: "backward",
    });
  });

  test("supplied 'backward' but transition is forward → reject with expected 'forward'", () => {
    expect(directionReconcile("backward", 2, 5)).toEqual({
      ok: false,
      expected: "forward",
    });
  });

  test("supplied 'forward' but transition is redo → reject with expected 'redo'", () => {
    expect(directionReconcile("forward", 4, 4)).toEqual({
      ok: false,
      expected: "redo",
    });
  });
});

// In-process drive of the resolve/execute handlers themselves — the pure-helper
// cases above cover the reconciliation math, but the handler bodies that CALL
// them (index derivation, the loud-reject error path) are only reachable through
// the CLI, which the spawn-driven t19 case cannot register in lcov. These drive
// the handlers directly against a seeded state fixture (state seed required so
// readStateFile / emitError resolve the active intent — inprocess-fixture-state-seed).

class ExitSignal extends Error {
  constructor(public readonly code: number) {
    super(`exit ${code}`);
  }
}

// error() ends the CLI via process.exit and writes the message via console.error;
// in-process we convert the exit into a throwable and capture stderr so the test
// can assert on the loud-reject path and keep running.
function captureExit(fn: () => void): { threw: boolean; stderr: string } {
  let stderr = "";
  const origExit = process.exit.bind(process);
  const origErr = console.error;
  const origLog = console.log;
  process.exit = ((code?: number) => {
    throw new ExitSignal(code ?? 0);
  }) as typeof process.exit;
  console.error = (...a: unknown[]) => {
    stderr += a.map(String).join(" ");
  };
  console.log = () => {};
  let threw = false;
  try {
    fn();
  } catch (e) {
    if (e instanceof ExitSignal) threw = true;
    else throw e;
  } finally {
    process.exit = origExit;
    console.error = origErr;
    console.log = origLog;
  }
  return { threw, stderr };
}

describe("t-jump-direction-seam: handler drive (FR-4, in-process)", () => {
  let proj: string;
  let prevProjectDir: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    seedStateFile(proj, "state-construction-bolt1.md");
    prevProjectDir = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prevProjectDir === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prevProjectDir;
    cleanupTestProject(proj);
  });

  test("resolve derives the forward direction and prints a plan (no exit)", () => {
    // Current Stage is functional-design; nfr-requirements is the next stage —
    // a forward resolve that runs the index derivation without erroring.
    const r = captureExit(() => handleResolve(["--stage", "nfr-requirements"]));
    expect(r.threw).toBe(false);
  });

  test("execute rejects a caller-supplied direction that disagrees with the graph", () => {
    // --direction forward to an EARLIER stage (requirements-analysis, inception)
    // than the current construction stage → the reconcile guard rejects loudly.
    const r = captureExit(() =>
      handleExecute([
        "--target",
        "requirements-analysis",
        "--direction",
        "forward",
      ]),
    );
    expect(r.threw).toBe(true);
    expect(r.stderr).toContain("Direction mismatch");
    expect(r.stderr).toContain("backward");
  });
});
