// In-process coverage seam for the #836 Phase Progress roll-up wiring (FR-3).
//
// The defect: only jump (#842) and init wrote the `## Phase Progress` roll-up.
// The advance / finalize / complete-workflow transitions crossed phase
// boundaries and emitted PHASE_COMPLETED/PHASE_VERIFIED/PHASE_STARTED into the
// append-only ledger, but never flipped the roll-up field — so a completed
// bugfix workflow (gate-start → approve → advance, where approve delegates to
// handleAdvance/handleCompleteWorkflow) ended at Status: Completed with the
// roll-up frozen at its init values (Initialization: Active / Construction:
// Pending). The fix flips the roll-up in the SAME content transaction as the
// field/audit updates, mirroring the jump precedent (amadeus-jump.ts).
//
// The handlers are spawn-driven end-to-end elsewhere (t17), which bun's coverage
// cannot see (the spawn blindspot). So this test imports them directly from the
// shipped dist tree (the #761 seam precedent — a stale dist reds here rather
// than passing against un-regenerated bytes) and drives the transitions
// in-process against seeded state. The suite-wide guards are also set here so
// the file passes when run bare.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  handleAdvance,
  handleCompleteWorkflow,
  handleFinalize,
} from "../../dist/claude/.claude/tools/amadeus-state.ts";
import {
  handleIntentBirth,
  initPhaseStatus,
} from "../../dist/claude/.claude/tools/amadeus-utility.ts";
import {
  cleanupTestProject,
  createTestProject,
  seededStateFile,
  seedStateFile,
} from "../harness/fixtures.ts";

// Resolve the born intent's state file from the active-intent cursor (birth
// mints a NEW intent; the seeded default record is not it).
function bornStateFile(proj: string): string {
  const intentsDir = join(proj, "amadeus", "spaces", "default", "intents");
  const cursor = join(intentsDir, "active-intent");
  const rec = existsSync(cursor) ? readFileSync(cursor, "utf-8").trim() : "";
  return join(intentsDir, rec, "amadeus-state.md");
}

process.env.AMADEUS_SKIP_ARTIFACT_GUARD ??= "1";
process.env.AMADEUS_SKIP_HUMAN_PRESENCE_GUARD ??= "1";

function readState(proj: string): string {
  return readFileSync(seededStateFile(proj), "utf-8");
}

// Extract a `- **<Phase>**: <status>` roll-up value, or "(missing)".
function phaseField(state: string, phase: string): string {
  const m = state.match(new RegExp(`^- \\*\\*${phase}\\*\\*: (\\w+)$`, "m"));
  return m ? m[1] : "(missing)";
}

describe("t-phase-progress-rollup-seam: advance across a phase boundary (#836)", () => {
  let proj: string;
  let prev: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    // scope=bugfix, Current Stage=requirements-analysis (inception, Active);
    // reverse-engineering already [x]. Advancing derives code-generation
    // (construction) → an inception→construction boundary crossing.
    seedStateFile(proj, "state-mid-inception.md");
    prev = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prev === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prev;
    cleanupTestProject(proj);
  });

  test("flips the closed phase → Verified and the entered phase → Active", () => {
    // Pre-state: Inception Active, Construction Pending (the un-wired bug froze
    // these). Single-arg advance derives the next in-scope stage.
    handleAdvance(["requirements-analysis"]);
    const state = readState(proj);
    expect(phaseField(state, "Inception")).toBe("Verified");
    expect(phaseField(state, "Construction")).toBe("Active");
    // Untouched phases keep their prior roll-up (per the seed fixture).
    expect(phaseField(state, "Initialization")).toBe("Verified");
    expect(phaseField(state, "Ideation")).toBe("Verified");
    expect(phaseField(state, "Operation")).toBe("Pending");
  });
});

describe("t-phase-progress-rollup-seam: complete-workflow verifies the final phase (#836 main repro)", () => {
  let proj: string;
  let prev: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    // scope=bugfix at the final construction stage (build-and-test [-]),
    // Construction Active. complete-workflow must flip it Verified in lock-step
    // with Status: Completed — the direct closure of the #836 symptom.
    seedStateFile(proj, "state-bugfix-final-construction.md");
    prev = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prev === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prev;
    cleanupTestProject(proj);
  });

  test("Construction → Verified and Status → Completed in the same transaction", () => {
    handleCompleteWorkflow(["build-and-test"]);
    const state = readState(proj);
    expect(phaseField(state, "Construction")).toBe("Verified");
    expect(state).toContain("- **Status**: Completed");
    // No residual Active/Pending anywhere in the roll-up (the #836 assertion).
    for (const p of ["Initialization", "Ideation", "Inception", "Construction", "Operation"]) {
      expect(["Verified", "Skipped"]).toContain(phaseField(state, p));
    }
  });
});

describe("t-phase-progress-rollup-seam: finalize verifies the final phase (#836)", () => {
  let proj: string;
  let prev: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    seedStateFile(proj, "state-bugfix-final-construction.md");
    prev = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prev === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prev;
    cleanupTestProject(proj);
  });

  test("terminal finalize flips the final phase Verified with Status: Completed", () => {
    // build-and-test is the last in-scope stage → nextInScopeStage returns null
    // → finalize takes the terminal branch (Status: Completed).
    handleFinalize(["build-and-test"]);
    const state = readState(proj);
    expect(phaseField(state, "Construction")).toBe("Verified");
    expect(state).toContain("- **Status**: Completed");
  });
});

describe("t-phase-progress-rollup-seam: finalize across a phase boundary (#836)", () => {
  let proj: string;
  let prev: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    // Current Stage=requirements-analysis (inception); finalize derives
    // code-generation (construction) as the next in-scope stage → a
    // boundary-crossing finalize (the non-terminal branch).
    seedStateFile(proj, "state-mid-inception.md");
    prev = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prev === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prev;
    cleanupTestProject(proj);
  });

  test("closes the completed phase → Verified and enters the next → Active", () => {
    handleFinalize(["requirements-analysis"]);
    const state = readState(proj);
    expect(phaseField(state, "Inception")).toBe("Verified");
    expect(phaseField(state, "Construction")).toBe("Active");
  });
});

describe("t-phase-progress-rollup-seam: full bugfix drive leaves no Active/Pending residue (#836 closure)", () => {
  let proj: string;
  let prev: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    // A faithful bugfix roll-up right after init (with the init fix applied):
    // Initialization Verified, Ideation/Operation Skipped, Inception Active.
    seedStateFile(proj, "state-bugfix-postinit.md");
    prev = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prev === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prev;
    cleanupTestProject(proj);
  });

  test("advance through the boundary, then complete-workflow, fully resolves the roll-up", () => {
    handleAdvance(["reverse-engineering"]); // within inception (no boundary)
    handleAdvance(["requirements-analysis"]); // inception → construction
    handleAdvance(["code-generation"]); // within construction (no boundary)
    handleCompleteWorkflow(["build-and-test"]); // terminal → Construction Verified
    const state = readState(proj);
    expect(phaseField(state, "Initialization")).toBe("Verified");
    expect(phaseField(state, "Ideation")).toBe("Skipped");
    expect(phaseField(state, "Inception")).toBe("Verified");
    expect(phaseField(state, "Construction")).toBe("Verified");
    expect(phaseField(state, "Operation")).toBe("Skipped");
    expect(state).toContain("- **Status**: Completed");
    // The #836 headline: no phase is left Active or Pending after completion.
    expect(state).not.toMatch(/^- \*\*(Initialization|Ideation|Inception|Construction|Operation)\*\*: (Active|Pending)$/m);
  });
});

describe("t-phase-progress-rollup-seam: init writes a pre-crossed roll-up in-process (#836 root)", () => {
  let proj: string;
  let prev: string | undefined;

  beforeEach(() => {
    proj = createTestProject();
    prev = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });

  afterEach(() => {
    if (prev === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prev;
    cleanupTestProject(proj);
  });

  test("bugfix birth stamps Initialization Verified (not Active) and Inception Active", () => {
    // Drive the real birth handler in-process (t39/t20 spawn it, which bun's
    // coverage cannot see — this seam registers the init phaseStatus wiring in
    // lcov). Birth pre-crosses initialization → inception for bugfix.
    handleIntentBirth(proj, { scope: "bugfix" });
    const state = readFileSync(bornStateFile(proj), "utf-8");
    expect(phaseField(state, "Initialization")).toBe("Verified");
    expect(phaseField(state, "Ideation")).toBe("Skipped");
    expect(phaseField(state, "Inception")).toBe("Active");
    expect(phaseField(state, "Construction")).toBe("Pending");
    expect(phaseField(state, "Operation")).toBe("Skipped");
    // The #836 headline at init time: initialization is NOT left Active.
    expect(state).not.toContain("- **Initialization**: Active");
  });
});

describe("t-phase-progress-rollup-seam: initPhaseStatus pure seam (#836 init pre-cross)", () => {
  // Init pre-crosses initialization → the first post-init phase. firstPostInit
  // in a later phase (the common case): initialization Verified, that phase
  // Active, others Pending/Skipped.
  test("crossed: initialization → Verified", () => {
    expect(initPhaseStatus("initialization", "inception", false)).toBe("Verified");
  });
  test("crossed: first post-init phase → Active", () => {
    expect(initPhaseStatus("inception", "inception", true)).toBe("Active");
  });
  test("crossed: later phase with EXECUTE work → Pending", () => {
    expect(initPhaseStatus("construction", "inception", true)).toBe("Pending");
  });
  test("crossed: phase with no EXECUTE work → Skipped", () => {
    expect(initPhaseStatus("operation", "inception", false)).toBe("Skipped");
  });
  test("not crossed (firstPostInit null): initialization stays Active", () => {
    expect(initPhaseStatus("initialization", null, false)).toBe("Active");
  });
});
