// Regression for issue #834 — the parked short-circuit (Branch 2.5) must let a
// `next --new-intent` pass through to the Branch 4a birth print.
//
// Defect: the Branch 2.5 guard (amadeus-orchestrate.ts) excluded `--resume`,
// `--stage`, `--phase` but NOT `--new-intent`. When the active-intent cursor
// points at a parked intent, `next --new-intent` was swallowed into a
// `{"kind":"parked"}` directive and never reached the birth print, so a brand-
// new intent could not be born beside a parked one. This is the sister of the
// #750/#832 latch-face `--new-intent` escape on a different code path.
//
// The behavioural RED/GREEN lives in the spawn-driven case (the shipped dist
// CLI, verbatim #834 reproduction). The in-process handler drive registers the
// added guard line in lcov (the spawn blindspot cannot — spawn-blindspot-seam-
// export / local-lcov-pre-push). Both import the SHIPPED dist tree, matching
// t-batch3-orchestrate-seam: a stale dist reds here rather than passing against
// un-regenerated bytes.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { handleNext } from "../../dist/claude/.claude/tools/amadeus-orchestrate.ts";
import {
  AMADEUS_SRC,
  cleanupTestProject,
  createTestProject,
  FIXTURES_DIR,
  resetAidlcEnv,
  seedStateFile,
} from "../harness/fixtures.ts";

const BUN = process.execPath;
const TOOL = join(AMADEUS_SRC, "tools", "amadeus-orchestrate.ts");
const STATE = join(AMADEUS_SRC, "tools", "amadeus-state.ts");
const MID_IDEATION = join(FIXTURES_DIR, "state-mid-ideation.md");

// `state park` writes the Parked marker (setup, not the code under test) so the
// active-intent cursor equivalent — a state file carrying a live Parked field —
// is present when `next` runs.
function park(p: string): void {
  spawnSync(BUN, [STATE, "park", "--project-dir", p], { encoding: "utf-8", cwd: p });
}

// The CLI handler ends error paths via process.exit and prints via console.log /
// console.error; in-process we convert the exit into a throwable and capture both.
class ExitSignal extends Error {
  constructor(public readonly code: number) {
    super(`exit ${code}`);
  }
}

function captureRun(fn: () => void): { exited: boolean; stdout: string; stderr: string } {
  let stdout = "";
  let stderr = "";
  const origExit = process.exit.bind(process);
  const origLog = console.log;
  const origErr = console.error;
  process.exit = ((code?: number) => {
    throw new ExitSignal(code ?? 0);
  }) as typeof process.exit;
  console.log = (...a: unknown[]) => {
    stdout += `${a.map(String).join(" ")}\n`;
  };
  console.error = (...a: unknown[]) => {
    stderr += `${a.map(String).join(" ")}\n`;
  };
  let exited = false;
  try {
    fn();
  } catch (e) {
    if (e instanceof ExitSignal) exited = true;
    else throw e;
  } finally {
    process.exit = origExit;
    console.log = origLog;
    console.error = origErr;
  }
  return { exited, stdout, stderr };
}

let proj = "";
beforeEach(() => {
  resetAidlcEnv();
  proj = createTestProject();
});
afterEach(() => {
  resetAidlcEnv();
  cleanupTestProject(proj);
  proj = "";
});

// --- Spawn-driven behavioural RED/GREEN (verbatim #834 reproduction) ---------
describe("t213 parked cursor + --new-intent (#834, spawn)", () => {
  function runNext(args: string[]): string {
    const res = spawnSync(BUN, [TOOL, "next", ...args, "--project-dir", proj], {
      encoding: "utf-8",
      cwd: proj,
      env: process.env,
    });
    return `${res.stdout ?? ""}${res.stderr ?? ""}`;
  }

  test("next --new-intent on a parked workflow reaches the birth print (not parked)", () => {
    // #834 reproduction: parked active-intent cursor. Pre-fix this returned
    // {"kind":"parked"}; post-fix it must pass through to the Branch 4a birth
    // print (which names `intent-birth`).
    seedStateFile(proj, MID_IDEATION);
    park(proj);
    const out = runNext(["--new-intent", "--scope", "bugfix"]);
    expect(out).not.toContain('"kind":"parked"');
    expect(out).toContain('"kind":"print"');
    expect(out).toContain("intent-birth");
  });

  test("plain next on a parked workflow still parks (unchanged)", () => {
    seedStateFile(proj, MID_IDEATION);
    park(proj);
    const out = runNext([]);
    expect(out).toContain('"kind":"parked"');
    expect(out).toContain('"stage":"feasibility"');
  });
});

// --- In-process handler drive (lcov registration of the added guard line) -----
describe("t213 parked cursor + --new-intent (#834, in-process seam)", () => {
  let prevProjectDir: string | undefined;
  beforeEach(() => {
    prevProjectDir = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = proj;
  });
  afterEach(() => {
    if (prevProjectDir === undefined) delete process.env.CLAUDE_PROJECT_DIR;
    else process.env.CLAUDE_PROJECT_DIR = prevProjectDir;
  });

  test("handleNext(--new-intent) over a parked state prints birth, not parked", () => {
    seedStateFile(proj, MID_IDEATION);
    park(proj);
    const r = captureRun(() => handleNext(["--new-intent", "--scope", "bugfix"], proj));
    expect(r.stdout).not.toContain('"kind":"parked"');
    expect(r.stdout).toContain("intent-birth");
  });

  test("handleNext() plain over a parked state prints the parked directive", () => {
    seedStateFile(proj, MID_IDEATION);
    park(proj);
    const r = captureRun(() => handleNext([], proj));
    expect(r.stdout).toContain('"kind":"parked"');
  });
});
