// covers: audit:ERROR_LOGGED
//
// In-process coverage seam for the engine ERROR_LOGGED recorder (#839).
//
// The spawn-driven integration twin (tests/integration/t214-engine-error-
// logged.test.ts) proves the end-to-end WIRING at the process boundary, but
// bun's coverage instrumentation cannot see through the spawn (the spawn
// blindspot). So this file imports the engine's helpers directly from the
// shipped dist tree and drives every added line in-process, so they register in
// lcov (local-lcov-pre-push / seam-export-handler-amend):
//   - recordEngineError body        — called directly.
//   - emit()'s `kind === "error"` branch — reached via handleNext(bogus scope),
//     which emits an error directive in-process.
//   - the top-level catch            — reached via runEngineMain() with a
//     malformed stage graph, process.exit stubbed to a throwable.
//
// Helpers are imported from dist/claude (matching the t-batch3-orchestrate-seam
// precedent) so a stale dist reds here rather than passing against
// un-regenerated bytes.
//
// recordEngineError contract: best-effort ONE ERROR_LOGGED row when workflow
// state exists; no-op (no throw, no write) when it does not. Project-dir
// resolution mirrors main(): --project-dir from process.argv, else
// CLAUDE_PROJECT_DIR.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  handleNext,
  recordEngineError,
  runEngineMain,
} from "../../dist/claude/.claude/tools/amadeus-orchestrate.ts";
import {
  cleanupTestProject,
  createTestProject,
  removeWorkspaceRecord,
  seededAuditShard,
  seedStateFile,
} from "../harness/fixtures.ts";

let proj: string | undefined;
let priorProjectDir: string | undefined;
let priorGraph: string | undefined;
let priorArgv: string[] | undefined;

beforeEach(() => {
  priorProjectDir = process.env.CLAUDE_PROJECT_DIR;
  priorGraph = process.env.AMADEUS_STAGE_GRAPH;
  priorArgv = process.argv;
});

afterEach(() => {
  const restore = (k: string, v: string | undefined) => {
    if (v === undefined) delete process.env[k];
    else process.env[k] = v;
  };
  restore("CLAUDE_PROJECT_DIR", priorProjectDir);
  restore("AMADEUS_STAGE_GRAPH", priorGraph);
  if (priorArgv) process.argv = priorArgv;
  cleanupTestProject(proj);
  proj = undefined;
});

function errorLoggedCount(p: string): number {
  const shard = seededAuditShard(p);
  if (!existsSync(shard)) return 0;
  return readFileSync(shard, "utf-8")
    .split("\n")
    .filter((l) => /^\*\*Event\*\*: ERROR_LOGGED$/.test(l)).length;
}

class ExitSignal extends Error {
  constructor(public readonly code: number) {
    super(`exit ${code}`);
  }
}

// Convert process.exit + console.* into captured values so an in-process run of
// a CLI error path does not tear down the test runner (t-batch3 precedent).
function captureRun(fn: () => void): { exited: boolean; stdout: string; stderr: string } {
  let stdout = "";
  let stderr = "";
  const origExit = process.exit.bind(process);
  const origLog = console.log;
  const origErr = console.error;
  process.exit = ((code?: number) => {
    throw new ExitSignal(code ?? 0);
  }) as typeof process.exit;
  console.log = (...a: unknown[]) => {
    stdout += `${a.map(String).join(" ")}\n`;
  };
  console.error = (...a: unknown[]) => {
    stderr += `${a.map(String).join(" ")}\n`;
  };
  let exited = false;
  try {
    fn();
  } catch (e) {
    if (e instanceof ExitSignal) exited = true;
    else throw e;
  } finally {
    process.exit = origExit;
    console.log = origLog;
    console.error = origErr;
  }
  return { exited, stdout, stderr };
}

describe("recordEngineError seam (#839)", () => {
  test("appends exactly one ERROR_LOGGED row when workflow state exists", () => {
    proj = createTestProject();
    seedStateFile(proj, "state-init-active.md");
    process.env.CLAUDE_PROJECT_DIR = proj;

    recordEngineError("seam: something went wrong");

    expect(errorLoggedCount(proj)).toBe(1);
    const shard = readFileSync(seededAuditShard(proj), "utf-8");
    expect(shard).toContain("amadeus-orchestrate");
    expect(shard).toContain("seam: something went wrong");
  });

  test("resolves the record from a --project-dir argv flag (main-parse-free path)", () => {
    proj = createTestProject();
    seedStateFile(proj, "state-init-active.md");
    // Drive the argv-extraction loop: no CLAUDE_PROJECT_DIR, project dir given
    // as a --project-dir flag the way main() receives it.
    delete process.env.CLAUDE_PROJECT_DIR;
    process.argv = ["bun", "amadeus-orchestrate.ts", "next", "--project-dir", proj];

    recordEngineError("seam: argv project-dir");

    expect(errorLoggedCount(proj)).toBe(1);
    expect(readFileSync(seededAuditShard(proj), "utf-8")).toContain("seam: argv project-dir");
  });

  test("is a no-op when no workflow state exists (pre-init error path)", () => {
    proj = createTestProject();
    removeWorkspaceRecord(proj); // drop the record + cursor: no state file
    process.env.CLAUDE_PROJECT_DIR = proj;

    expect(() => recordEngineError("seam: no state")).not.toThrow();
    expect(errorLoggedCount(proj)).toBe(0);
  });
});

describe("emit() error-directive branch records ERROR_LOGGED (#839)", () => {
  test("an unknown-scope error directive appends an ERROR_LOGGED row in-process", () => {
    proj = createTestProject();
    seedStateFile(proj, "state-init-active.md");
    process.env.CLAUDE_PROJECT_DIR = proj;

    // handleNext reaches emit(errorDirective("Unknown scope ...")); emit()'s
    // kind==="error" branch calls recordEngineError before printing the JSON.
    const run = captureRun(() => handleNext(["--scope", "zzznotascope"], proj));

    expect(run.exited).toBe(false); // an error directive does NOT exit
    const directive = JSON.parse(run.stdout.trim());
    expect(directive.kind).toBe("error");
    expect(directive.message).toContain("Unknown scope");
    expect(errorLoggedCount(proj)).toBe(1);
  });
});

describe("top-level catch records ERROR_LOGGED (#839)", () => {
  test("a malformed stage graph throw records ERROR_LOGGED then exits 1", () => {
    proj = createTestProject();
    seedStateFile(proj, "state-init-active.md");
    process.env.CLAUDE_PROJECT_DIR = proj;
    process.argv = ["bun", "amadeus-orchestrate.ts", "next", "--project-dir", proj];
    // Point loadStageGraph() at malformed JSON so main() throws into the catch.
    const badGraph = join(proj, "bad-stage-graph.json");
    writeFileSync(badGraph, "this is not valid json {", "utf-8");
    process.env.AMADEUS_STAGE_GRAPH = badGraph;

    const run = captureRun(() => runEngineMain());

    expect(run.exited).toBe(true); // the catch exits 1
    expect(run.stderr).toContain("amadeus-orchestrate:");
    expect(errorLoggedCount(proj)).toBe(1);
  });
});
