// covers: audit:ERROR_LOGGED
//
// In-process coverage seam for the engine main() default (Unknown subcommand)
// exit (#878). Sibling class of #839 (t214): the emit⇔terminal asymmetry where
// the engine's own terminal exits printed to stderr without leaving an
// ERROR_LOGGED row. #839 wired the top-level catch and the error-directive
// emit; this file covers the remaining default-case exit that was unwired since
// bootstrap.
//
// The default-case exit is driven in-process via the runEngineMain() seam with
// an unknown subcommand in process.argv, so bun's coverage instrumentation sees
// the added recordEngineError wiring (the spawn blindspot hides the process
// boundary). process.exit is stubbed to a throwable so the CLI error path does
// not tear down the test runner (t214 / t-batch3-orchestrate-seam precedent).
//
// Helpers are imported from dist/claude (matching t214) so a stale dist reds
// here rather than passing against un-regenerated bytes.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { runEngineMain } from "../../dist/claude/.claude/tools/amadeus-orchestrate.ts";
import {
  cleanupTestProject,
  createTestProject,
  removeWorkspaceRecord,
  seededAuditShard,
  seedStateFile,
} from "../harness/fixtures.ts";

let proj: string | undefined;
let priorProjectDir: string | undefined;
let priorArgv: string[] | undefined;

beforeEach(() => {
  priorProjectDir = process.env.CLAUDE_PROJECT_DIR;
  priorArgv = process.argv;
});

afterEach(() => {
  if (priorProjectDir === undefined) delete process.env.CLAUDE_PROJECT_DIR;
  else process.env.CLAUDE_PROJECT_DIR = priorProjectDir;
  if (priorArgv) process.argv = priorArgv;
  cleanupTestProject(proj);
  proj = undefined;
});

function errorLoggedCount(p: string): number {
  const shard = seededAuditShard(p);
  if (!existsSync(shard)) return 0;
  return readFileSync(shard, "utf-8")
    .split("\n")
    .filter((l) => /^\*\*Event\*\*: ERROR_LOGGED$/.test(l)).length;
}

// Count default-case ERROR_LOGGED rows specifically. Driving the default exit
// through runEngineMain in-process makes the stubbed process.exit throw, which
// runEngineMain's top-level catch re-records as a second row carrying the
// ExitSignal ("exit 1") message — an artifact of the stub that never happens
// under a real spawn (process.exit halts, the catch never runs). Scoping to the
// default-case message isolates the FR-1 wiring: 0 pre-fix, exactly 1 post-fix.
function defaultExitErrorRows(p: string): number {
  const shard = seededAuditShard(p);
  if (!existsSync(shard)) return 0;
  return readFileSync(shard, "utf-8")
    .split("\n")
    .filter((l) => l.includes("Unknown subcommand: nosuchcommand")).length;
}

class ExitSignal extends Error {
  constructor(public readonly code: number) {
    super(`exit ${code}`);
  }
}

// Convert process.exit + console.* into captured values so an in-process run of
// a CLI error path does not tear down the test runner (t214 precedent).
function captureRun(fn: () => void): { exited: boolean; code: number; stderr: string } {
  let stderr = "";
  let code = 0;
  const origExit = process.exit.bind(process);
  const origLog = console.log;
  const origErr = console.error;
  process.exit = ((c?: number) => {
    throw new ExitSignal(c ?? 0);
  }) as typeof process.exit;
  console.log = () => {};
  console.error = (...a: unknown[]) => {
    stderr += `${a.map(String).join(" ")}\n`;
  };
  let exited = false;
  try {
    fn();
  } catch (e) {
    if (e instanceof ExitSignal) {
      exited = true;
      code = e.code;
    } else throw e;
  } finally {
    process.exit = origExit;
    console.log = origLog;
    console.error = origErr;
  }
  return { exited, code, stderr };
}

describe("main() default exit records ERROR_LOGGED (#878)", () => {
  test("an unknown subcommand records exactly one ERROR_LOGGED row then exits 1", () => {
    proj = createTestProject();
    seedStateFile(proj, "state-init-active.md");
    process.env.CLAUDE_PROJECT_DIR = proj;
    process.argv = ["bun", "amadeus-orchestrate.ts", "nosuchcommand", "--project-dir", proj];

    const run = captureRun(() => runEngineMain());

    expect(run.exited).toBe(true); // the default case exits
    expect(run.code).toBe(1); // ...with code 1
    expect(run.stderr).toContain("Unknown subcommand: nosuchcommand");
    expect(defaultExitErrorRows(proj)).toBe(1);
    const shard = readFileSync(seededAuditShard(proj), "utf-8");
    expect(shard).toContain("amadeus-orchestrate");
    expect(shard).toContain("Unknown subcommand: nosuchcommand");
  });

  test("is a no-op on the record when no workflow state exists (pre-init path)", () => {
    proj = createTestProject();
    removeWorkspaceRecord(proj); // drop the record + cursor: no state file
    process.env.CLAUDE_PROJECT_DIR = proj;
    process.argv = ["bun", "amadeus-orchestrate.ts", "nosuchcommand", "--project-dir", proj];

    const run = captureRun(() => runEngineMain());

    expect(run.exited).toBe(true); // still exits 1 (stderr + exit unchanged)
    expect(run.code).toBe(1);
    expect(run.stderr).toContain("Unknown subcommand: nosuchcommand");
    expect(errorLoggedCount(proj)).toBe(0); // ...but no ERROR_LOGGED row written
  });
});
