// covers: audit:AUDIT_FORKED
//
// In-process coverage seam for the audit-fork RE-ENTRY decision (Issue #850,
// restoring #478 gap1). A worktree audit shard is a tracked file: a re-created
// Bolt worktree checks out a committed copy of the main shard, so audit-fork
// must NOT treat "shard already exists" as a one-shot violation. The restored
// contract:
//   - wt shard IS a byte-prefix of (or identical to) the main shard
//       -> Reentrant fork: allow, tag the AUDIT_FORKED row with Reentrant=true.
//   - wt shard is NOT a prefix (DIVERGED)
//       -> refuse (jsonError -> exit 1) with NO audit side effect.
//   - wt shard absent (first fork)
//       -> allow, plain AUDIT_FORKED (no Reentrant tag) — non-regression.
//
// The spawn-driven twin (tests/e2e/t07-audit-fork-merge) proves the wiring at
// the process boundary, but bun's coverage cannot see through the spawn (the
// spawn blindspot). So this file imports handleAuditFork directly from the
// shipped dist tree and drives all three branches in-process, so the added
// prefix-compare / DIVERGED / Reentrant-tag lines register in lcov
// (local-lcov-pre-push / seam-export-handler-amend). Helpers come from
// dist/claude so a stale dist reds here rather than passing against
// un-regenerated bytes.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { handleAuditFork } from "../../dist/claude/.claude/tools/amadeus-audit.ts";
import {
  auditFilePath,
  relativeRecordDir,
  worktreeAuditFilePath,
  worktreePath,
} from "../../dist/claude/.claude/tools/amadeus-lib.ts";
import {
  cleanupTestProject,
  createTestProject,
  seededAuditShard,
  seedStateFile,
} from "../harness/fixtures.ts";

let proj: string | undefined;
let priorProjectDir: string | undefined;

beforeEach(() => {
  priorProjectDir = process.env.CLAUDE_PROJECT_DIR;
});

afterEach(() => {
  if (priorProjectDir === undefined) delete process.env.CLAUDE_PROJECT_DIR;
  else process.env.CLAUDE_PROJECT_DIR = priorProjectDir;
  cleanupTestProject(proj);
  proj = undefined;
});

// --- exit/stdout/stderr capture (t214 precedent; jsonError/jsonSuccess in
// amadeus-audit.ts write via process.stdout/stderr.write and exit(1)). ---------
class ExitSignal extends Error {
  constructor(public readonly code: number) {
    super(`exit ${code}`);
  }
}

function captureRun(fn: () => void): {
  exited: boolean;
  stdout: string;
  stderr: string;
} {
  let stdout = "";
  let stderr = "";
  const origExit = process.exit.bind(process);
  const origOut = process.stdout.write.bind(process.stdout);
  const origErr = process.stderr.write.bind(process.stderr);
  process.exit = ((code?: number) => {
    throw new ExitSignal(code ?? 0);
  }) as typeof process.exit;
  process.stdout.write = ((chunk: unknown) => {
    stdout += String(chunk);
    return true;
  }) as typeof process.stdout.write;
  process.stderr.write = ((chunk: unknown) => {
    stderr += String(chunk);
    return true;
  }) as typeof process.stderr.write;
  let exited = false;
  try {
    fn();
  } catch (e) {
    if (e instanceof ExitSignal) exited = true;
    else throw e;
  } finally {
    process.exit = origExit;
    process.stdout.write = origOut;
    process.stderr.write = origErr;
  }
  return { exited, stdout, stderr };
}

// The main audit trail the tool resolves under default (active-intent)
// resolution IS the seeded per-clone shard. Seed it with a two-line ledger so a
// prefix (line one) is a genuine older snapshot and a divergent body is not.
const MAIN_LEDGER = "# AI-DLC Audit Log\n\n**Event**: SEEDED\n";
const PREFIX_OF_MAIN = "# AI-DLC Audit Log\n"; // byte-prefix of MAIN_LEDGER
const DIVERGED_LEDGER = "# A DIFFERENT LEDGER\n\n**Event**: OTHER\n"; // not a prefix

function seedProject(): string {
  const p = createTestProject();
  seedStateFile(p, "state-init-active.md");
  process.env.CLAUDE_PROJECT_DIR = p;
  // Main-side audit shard (what auditFilePath resolves to with the active intent).
  const mainShard = seededAuditShard(p);
  mkdirSync(dirname(mainShard), { recursive: true });
  writeFileSync(mainShard, MAIN_LEDGER, "utf-8");
  return p;
}

const SLUG = "u6-reentrant";

// Resolve the worktree shard path exactly as the handler does, then ensure the
// worktree directory exists so the "directory exists" pre-emit guard passes.
function wtShardPath(p: string): string {
  const wtPath = worktreePath(p, SLUG);
  mkdirSync(wtPath, { recursive: true });
  return worktreeAuditFilePath(wtPath, relativeRecordDir(p), p);
}

function seedWtShard(p: string, content: string): string {
  const wtShard = wtShardPath(p);
  mkdirSync(dirname(wtShard), { recursive: true });
  writeFileSync(wtShard, content, "utf-8");
  return wtShard;
}

function mainForkedRows(p: string): string[] {
  const shard = readFileSync(auditFilePath(p), "utf-8");
  // Split into blocks and keep the ones announcing an AUDIT_FORKED event.
  return shard
    .split(/\n(?=\*\*Event\*\*:)/)
    .filter((b) => /^\*\*Event\*\*: AUDIT_FORKED\b/.test(b.trimStart()));
}

describe("audit-fork re-entry (Issue #850, #478 gap1)", () => {
  test("(i) reentrant: wt shard is a prefix of main -> allow + Reentrant tag", () => {
    proj = seedProject();
    const wtShard = seedWtShard(proj, PREFIX_OF_MAIN);

    const run = captureRun(() => handleAuditFork(["--slug", SLUG], proj as string));

    // Post-fix contract: fork proceeds (no exit), success JSON on stdout.
    expect(run.exited).toBe(false);
    const out = JSON.parse(run.stdout.trim());
    expect(out.emitted).toBe("AUDIT_FORKED");
    expect(out.slug).toBe(SLUG);
    // The re-entry is audited distinctly from an initial fork.
    const forked = mainForkedRows(proj as string);
    expect(forked.length).toBe(1);
    expect(forked[0]).toContain("**Reentrant**: true");
    // The worktree shard is refreshed from main (copy happened).
    expect(readFileSync(wtShard, "utf-8")).toContain("**Event**: AUDIT_FORKED");
  });

  test("(ii) DIVERGED: wt shard is not a prefix -> refuse, no audit side effect", () => {
    proj = seedProject();
    seedWtShard(proj, DIVERGED_LEDGER);

    const run = captureRun(() => handleAuditFork(["--slug", SLUG], proj as string));

    // Refusal: exit 1, DIVERGED message, and (preflight-before-side-effect) NO
    // AUDIT_FORKED row landed in the main shard.
    expect(run.exited).toBe(true);
    expect(run.stderr).toContain("DIVERGED");
    expect(mainForkedRows(proj as string).length).toBe(0);
  });

  test("(iii) first fork: no wt shard -> allow, plain AUDIT_FORKED (no Reentrant)", () => {
    proj = seedProject();
    // Ensure the worktree DIR exists but no shard (non-regression path).
    const wtShard = wtShardPath(proj);
    expect(existsSync(wtShard)).toBe(false);

    const run = captureRun(() => handleAuditFork(["--slug", SLUG], proj as string));

    expect(run.exited).toBe(false);
    const out = JSON.parse(run.stdout.trim());
    expect(out.emitted).toBe("AUDIT_FORKED");
    const forked = mainForkedRows(proj as string);
    expect(forked.length).toBe(1);
    expect(forked[0]).not.toContain("Reentrant");
    // The initial copy created the worktree shard.
    expect(existsSync(wtShard)).toBe(true);
  });
});
