// covers: function:normalizeWorktreeSlug
//
// In-process coverage seam for the worktree-slug lowercase canonicalization
// (Issue #885, restoring #478 gap2). Record-side display names arrive in their
// display casing (e.g. unit names like "U101-Foo" per the Unnn-<slug> naming
// convention). Derived artifacts — worktree dirs, branch names, and the audit
// shard path nested under the worktree dir — MUST be lowercase kebab-case: on
// case-insensitive filesystems (macOS default) two casings would collide
// silently. The restored contract funnels every slug through ONE canonical
// lowercase choke point (normalizeWorktreeSlug):
//   - normalizeWorktreeSlug(slug)  -> slug.toLowerCase() (idempotent).
//   - worktreePath                 -> leaf is bolt-<lowercased-slug>.
//   - validateBoltSlug             -> BOLT_SLUG_REGEX judged post-normalization
//                                     (uppercase accepted; truly invalid still
//                                     rejected).
//   - the CLI validateSlug guards in amadeus-state.ts / amadeus-worktree.ts ->
//                                     return the normalized slug so the full
//                                     `bolt start --worktree` chain (state fork
//                                     -> audit-fork) stays lowercase-consistent.
//
// The spawn-driven twins (t76 state fork/merge, t77 bolt worktree lifecycle)
// prove the wiring at the process boundary, but bun's coverage cannot see
// through the spawn (the spawn blindspot). So this file imports the pure choke
// point plus the two CLI validateSlug guards directly from the shipped dist
// tree and drives them in-process, so the added normalization lines register in
// lcov (local-lcov-pre-push / seam-export-handler-amend). Helpers come from
// dist/claude so a stale dist reds here rather than passing against
// un-regenerated bytes.

import { describe, expect, test } from "bun:test";
import {
  normalizeWorktreeSlug,
  validateBoltSlug,
  worktreePath,
} from "../../dist/claude/.claude/tools/amadeus-lib.ts";
import { validateSlug as stateValidateSlug } from "../../dist/claude/.claude/tools/amadeus-state.ts";
import { validateSlug as worktreeValidateSlug } from "../../dist/claude/.claude/tools/amadeus-worktree.ts";

const PROJ = "/tmp/proj";
const portablePath = (p: string): string => p.replace(/\\/g, "/");
const leaf = (p: string): string => portablePath(p).split("/").pop() ?? "";

describe("normalizeWorktreeSlug — lowercase canonical form", () => {
  test("lowercases an uppercase-bearing display slug", () => {
    expect(normalizeWorktreeSlug("U101-Foo")).toBe("u101-foo");
  });

  // Non-regression: an already-lowercase slug is a no-op (existing kebab-case
  // Bolt slugs must pass through byte-identical).
  test("is a no-op on an already-lowercase slug", () => {
    expect(normalizeWorktreeSlug("mint-presence-vectors")).toBe(
      "mint-presence-vectors",
    );
  });

  test("is idempotent", () => {
    const once = normalizeWorktreeSlug("U101-Foo");
    expect(normalizeWorktreeSlug(once)).toBe(once);
  });
});

describe("validateBoltSlug — judged post-normalization", () => {
  // #885 restored behaviour: an uppercase-bearing Unit name is ACCEPTED because
  // its normalized form matches BOLT_SLUG_REGEX (pre-fix it was rejected).
  test("accepts an uppercase-bearing slug (Unnn-<slug> form)", () => {
    expect(validateBoltSlug("U101-Foo")).toBeNull();
  });

  // Non-regression: an already-lowercase valid slug still passes.
  test("accepts an already-lowercase slug (no-op)", () => {
    expect(validateBoltSlug("demo")).toBeNull();
  });

  // Still rejects a slug that is invalid even after normalization (starts with
  // a digit) — normalization only folds case, it does not sanitise structure.
  test("rejects a slug that is invalid after normalization", () => {
    const err = validateBoltSlug("1bad");
    expect(err).not.toBeNull();
    expect(err).toContain("must normalize to");
  });

  test("rejects a slug with an interior space after normalization", () => {
    expect(validateBoltSlug("U1 Foo")).not.toBeNull();
  });
});

describe("worktreePath — derived leaf is lowercase", () => {
  // The worktree dir (and the audit shard nested under it) inherit the
  // lowercase leaf, so two casings cannot collide on a case-insensitive FS.
  test("lowercases the bolt-<slug> leaf for an uppercase input", () => {
    expect(leaf(worktreePath(PROJ, "U101-Foo"))).toBe("bolt-u101-foo");
  });

  // Non-regression: a lowercase slug keeps its exact leaf.
  test("keeps the leaf byte-identical for a lowercase input", () => {
    expect(leaf(worktreePath(PROJ, "demo"))).toBe("bolt-demo");
  });
});

describe("CLI validateSlug guards return the normalized slug", () => {
  // amadeus-state.ts guard (state fork path).
  test("state validateSlug normalizes an uppercase slug", () => {
    expect(stateValidateSlug("U101-Foo")).toBe("u101-foo");
  });

  test("state validateSlug is a no-op on a lowercase slug", () => {
    expect(stateValidateSlug("demo")).toBe("demo");
  });

  // amadeus-worktree.ts guard (worktree create path).
  test("worktree validateSlug normalizes an uppercase slug", () => {
    expect(worktreeValidateSlug("U101-Foo")).toBe("u101-foo");
  });

  test("worktree validateSlug is a no-op on a lowercase slug", () => {
    expect(worktreeValidateSlug("demo")).toBe("demo");
  });
});
