// covers: harness-instrument:metrics-visualize
// Pure-function half of the metrics visualizer (U1 visualize-skeleton): arg
// parsing, numeric extraction, SVG path building, escaping, and the rendered
// document's contracts (all collectors present, SHA reachability, no external
// references, deterministic output). No spawn, no fs — the CLI/fs boundary
// lives in tests/integration/t298-metrics-visualize.integration.test.ts.
import { describe, expect, test } from "bun:test";
import type { Snapshot } from "../../scripts/metrics-timeseries";
import { formatValue, numericValue } from "../../scripts/metrics-timeseries";
import { escapeHtml, main, parseArgs, renderHtml, svgLinePath } from "../../scripts/metrics-visualize";

function snapshot(capturedAt: string, commit: string, values: Record<string, unknown>): Snapshot {
  return {
    schema_version: 1,
    captured_at: capturedAt,
    commit,
    collectors: { coverage: { tool: "bun", tool_version: "1.3.13", values } },
  };
}

const SERIES: Snapshot[] = [
  snapshot("2026-07-01T00:00:00.000Z", "a".repeat(40), { percent: 80.5, hits: 100 }),
  snapshot("2026-07-02T00:00:00.000Z", "b".repeat(40), { percent: 81.25, hits: 110 }),
];

describe("parseArgs", () => {
  test("--write is the only accepted form", () => {
    expect(parseArgs(["--write"])).toEqual({ kind: "ok", mode: "write" });
  });
  test("no arguments is a usage error", () => {
    const out = parseArgs([]);
    expect(out.kind).toBe("usage");
  });
  test("unknown flags are usage errors with the offending input named", () => {
    const out = parseArgs(["--nonsense"]);
    if (out.kind !== "usage") throw new Error("expected usage");
    expect(out.reason).toContain("--nonsense");
  });
  test("--check is accepted (U2)", () => {
    expect(parseArgs(["--check"])).toEqual({ kind: "ok", mode: "check" });
  });
});

describe("numericValue", () => {
  test("finite numbers pass through", () => {
    expect(numericValue(42.5)).toBe(42.5);
    expect(numericValue(0)).toBe(0);
  });
  test("NaN, Infinity, and non-numbers become null (gaps, never coordinates)", () => {
    expect(numericValue(Number.NaN)).toBeNull();
    expect(numericValue(Number.POSITIVE_INFINITY)).toBeNull();
    expect(numericValue("12")).toBeNull();
    expect(numericValue(undefined)).toBeNull();
  });
});

describe("formatValue export", () => {
  test("numbers render verbatim, absent renders empty, non-numbers render ?", () => {
    expect(formatValue(3)).toBe("3");
    expect(formatValue(undefined)).toBe("");
    expect(formatValue("x")).toBe("?");
  });
});

describe("svgLinePath", () => {
  test("a null breaks the line into separate segments", () => {
    const d = svgLinePath([1, 2, null, 3, 4], 720, 120);
    expect(d.match(/M/g)?.length).toBe(2);
    expect(d.match(/L/g)?.length).toBe(2);
  });
  test("a single point emits one M command and no L", () => {
    const d = svgLinePath([5], 720, 120);
    expect(d.startsWith("M")).toBe(true);
    expect(d).not.toContain("L");
  });
  test("a flat series (min === max) renders at the vertical center", () => {
    const d = svgLinePath([7, 7], 720, 120);
    expect(d).toContain(" 60.0");
  });
  test("all-null input renders an empty path", () => {
    expect(svgLinePath([null, null], 720, 120)).toBe("");
  });
});

describe("escapeHtml", () => {
  test("all five HTML-significant characters are escaped", () => {
    expect(escapeHtml(`&<>"'`)).toBe("&amp;&lt;&gt;&quot;&#39;");
  });
});

describe("renderHtml", () => {
  const html = renderHtml(SERIES);
  test("every discovered collector appears as a section heading", () => {
    expect(html).toContain("<h2>coverage");
  });
  test("data points carry captured_at + 12-char commit in their title (SHA reachability)", () => {
    expect(html).toContain("aaaaaaaaaaaa");
    expect(html).toContain("2026-07-01T00:00:00.000Z / aaaaaaaaaaaa");
  });
  test("the document is self-contained: no external references", () => {
    expect(html).not.toContain("http://");
    expect(html).not.toContain("https://");
  });
  test("the generated marker header is present", () => {
    expect(html.startsWith("<!-- generated by scripts/metrics-visualize.ts")).toBe(true);
  });
  test("rendering is deterministic: same input, same bytes", () => {
    expect(renderHtml(SERIES)).toBe(html);
  });
  test("non-numeric values render as gaps, not coordinates", () => {
    const withBadValue = [snapshot("2026-07-03T00:00:00.000Z", "c".repeat(40), { percent: "broken" })];
    const out = renderHtml(withBadValue);
    expect(out).toContain("データなし");
    expect(out).not.toContain("NaN");
  });
});

describe("main usage path", () => {
  test("unknown argv returns 2 without touching the filesystem", () => {
    expect(main(["--nonsense"])).toBe(2);
  });
});

// --- U2 (visualize-hardening) additions -------------------------------------

import { METRICS_RETENTION_KEEP_LAST } from "../../scripts/metrics-retention";
import { serializeSnapshot } from "../../scripts/metrics-snapshot";
import { MAX_HTML_BYTES, regressionClass } from "../../scripts/metrics-visualize";

function pair(collector: string, prevValues: Record<string, unknown>, currValues: Record<string, unknown>): Snapshot[] {
  const mk = (capturedAt: string, commit: string, values: Record<string, unknown>): Snapshot => ({
    schema_version: 1,
    captured_at: capturedAt,
    commit,
    collectors: { [collector]: { tool: "t", tool_version: "1", values } },
  });
  return [mk("2026-07-01T00:00:00.000Z", "a".repeat(40), prevValues), mk("2026-07-02T00:00:00.000Z", "b".repeat(40), currValues)];
}

describe("regressionClass", () => {
  test("worsening directions classify as regressed (both sides measured)", () => {
    expect(regressionClass("ccn", "over_threshold", 10, 12)).toBe("regressed");
    expect(regressionClass("ccn", "over_threshold", 12, 10)).toBe("");
    expect(regressionClass("ccn", "max", 30, 35)).toBe("regressed");
    expect(regressionClass("coverage", "percent", 81, 80)).toBe("regressed");
    expect(regressionClass("coverage", "percent", 80, 81)).toBe("");
    expect(regressionClass("dist_size", "bytes", 100, 200)).toBe("regressed");
  });
  test("failure counters are prev-agnostic: non-zero is always regressed", () => {
    expect(regressionClass("tests", "failedFiles", undefined, 1)).toBe("regressed");
    expect(regressionClass("tests", "failedAssertions", 0, 2)).toBe("regressed");
    expect(regressionClass("tests", "failedFiles", 5, 0)).toBe("");
  });
  test("unknown collectors/keys and non-numeric values never classify", () => {
    expect(regressionClass("unknown", "anything", 1, 2)).toBe("");
    expect(regressionClass("ccn", "p50", 1, 2)).toBe("");
    expect(regressionClass("ccn", "over_threshold", 10, "broken")).toBe("");
    expect(regressionClass("ccn", "over_threshold", null, 12)).toBe("");
  });
});

describe("renderHtml regression highlighting", () => {
  test("a worsening latest value carries the regressed class (chart + table)", () => {
    const html = renderHtml(pair("coverage", { percent: 81 }, { percent: 80 }));
    expect(html).toContain('circle class="regressed"');
    expect(html).toContain('td class="regressed"');
  });
  test("a non-worsening latest value carries no regressed class", () => {
    const html = renderHtml(pair("coverage", { percent: 80 }, { percent: 81 }));
    expect(html).not.toContain('class="regressed"');
  });
  test("the legend line is present and static", () => {
    const html = renderHtml(pair("coverage", { percent: 80 }, { percent: 81 }));
    expect(html).toContain("直前スナップショットからの劣化");
  });
});

describe("MAX_HTML_BYTES", () => {
  test("derives from the retention constant times the snapshot cap times 2", () => {
    expect(MAX_HTML_BYTES).toBe(16_384 * METRICS_RETENTION_KEEP_LAST * 2);
  });
  test("the 16_384 mirror is pinned to the writer's real serialization cap", () => {
    const big: Snapshot = {
      schema_version: 1,
      captured_at: "2026-07-01T00:00:00.000Z",
      commit: "a".repeat(40),
      collectors: {
        pad: { tool: "t", tool_version: "1", values: { filler: 0, note: "x".repeat(17_000) } as Record<string, unknown> },
      },
    };
    expect(() => serializeSnapshot(big)).toThrow("16384");
    const small: Snapshot = { schema_version: 1, captured_at: "2026-07-01T00:00:00.000Z", commit: "a".repeat(40), collectors: {} };
    expect(() => serializeSnapshot(small)).not.toThrow();
  });
});
