// covers: audit:formatAuditRecord audit:fork-merge-seams state:compaction-detect
//
// In-process coverage for the format-neutral audit seams introduced by the
// Issue #1628 groundwork (PR-1): the canonical record formatter, the shared
// record splitter, the fork/merge physical-representation helpers, and the
// structured compaction detector. All pure functions — no filesystem, no
// spawn. Imports come from the shipped dist tree so a stale dist reds here
// rather than passing against un-regenerated bytes (t219 precedent).

import { describe, expect, test } from "bun:test";
import {
  auditPrefixMismatch,
  countDeltaRecords,
  extractPostForkDelta,
  findForkAnchor,
  formatAuditRecord,
} from "../../dist/claude/.claude/tools/amadeus-audit.ts";
import { splitAuditRecords } from "../../dist/claude/.claude/tools/amadeus-lib.ts";
import { compactionPendingFromAudit } from "../../dist/claude/.claude/tools/amadeus-state.ts";
import { createHash } from "node:crypto";

describe("formatAuditRecord — the one canonical record renderer", () => {
  test("event + fields render byte-identically to the historical inline builders", () => {
    const block = formatAuditRecord({
      heading: "Stage Start",
      timestamp: "2026-07-28T10:00:00Z",
      event: "STAGE_STARTED",
      fields: { Stage: "code-generation", Agent: "developer" },
    });
    expect(block).toBe(
      "\n## Stage Start\n**Timestamp**: 2026-07-28T10:00:00Z\n**Event**: STAGE_STARTED\n**Stage**: code-generation\n**Agent**: developer\n\n---\n",
    );
  });

  test("field values are newline-escaped (audit forgery guard preserved)", () => {
    const block = formatAuditRecord({
      heading: "Error",
      timestamp: "2026-07-28T10:00:00Z",
      event: "ERROR_LOGGED",
      fields: { Error: "line1\nline2\r\nline3" },
    });
    expect(block).toContain("**Error**: line1\\nline2\\nline3\n");
  });

  test("rawBody renders the append-raw shape (no Event line)", () => {
    const block = formatAuditRecord({
      heading: "Custom Note",
      timestamp: "2026-07-28T10:00:00Z",
      rawBody: "**Note**: free-form",
    });
    expect(block).toBe(
      "\n## Custom Note\n**Timestamp**: 2026-07-28T10:00:00Z\n**Note**: free-form\n\n---\n",
    );
  });
});

describe("splitAuditRecords — the one record-boundary splitter", () => {
  test("splits on the record separator and normalises CRLF", () => {
    const a = formatAuditRecord({ heading: "A", timestamp: "t1", event: "HUMAN_TURN" });
    const b = formatAuditRecord({ heading: "B", timestamp: "t2", event: "HUMAN_TURN" });
    const crlf = (a + b).replace(/\n/g, "\r\n");
    const blocks = splitAuditRecords(crlf).filter((blk: string) => blk.includes("**Event**"));
    expect(blocks.length).toBe(2);
    expect(blocks[0]).toContain("## A");
    expect(blocks[1]).toContain("## B");
  });
});

// A worktree shard: seeded prefix + AUDIT_FORKED anchor + two delta records.
const FORK_BLOCK_FIELDS = {
  "Bolt slug": "u1-demo",
  "Source Audit Hash": "ab12cd34".repeat(8),
  "Fork Boundary": "123",
};
const anchorBlock = formatAuditRecord({
  heading: "Audit Forked",
  timestamp: "2026-07-28T11:00:00Z",
  event: "AUDIT_FORKED",
  fields: FORK_BLOCK_FIELDS,
});
const deltaA = formatAuditRecord({
  heading: "Bolt Start",
  timestamp: "2026-07-28T11:01:00Z",
  event: "BOLT_STARTED",
  fields: { "Bolt slug": "u1-demo" },
});
const deltaB = formatAuditRecord({
  heading: "Bolt Completion",
  timestamp: "2026-07-28T11:02:00Z",
  event: "BOLT_COMPLETED",
  fields: { "Bolt slug": "u1-demo" },
});
const WT_SHARD = `# AI-DLC Audit Log\n${anchorBlock}${deltaA}${deltaB}`;

describe("findForkAnchor — AUDIT_FORKED anchor recovery", () => {
  test("recovers boundary, source hash, and fork timestamp for the slug", () => {
    const anchor = findForkAnchor(WT_SHARD, "u1-demo");
    expect(anchor).not.toBeNull();
    expect(anchor!.boundary).toBe(123);
    expect(anchor!.sourceHash).toBe("ab12cd34".repeat(8));
    expect(anchor!.forkTs).toBe("2026-07-28T11:00:00Z");
  });

  test("returns null when no AUDIT_FORKED entry matches the slug", () => {
    expect(findForkAnchor(WT_SHARD, "other-slug")).toBeNull();
    expect(findForkAnchor("# AI-DLC Audit Log\n", "u1-demo")).toBeNull();
  });

  test("throws on a present-but-malformed anchor (missing Fork Boundary)", () => {
    const malformed = formatAuditRecord({
      heading: "Audit Forked",
      timestamp: "2026-07-28T11:00:00Z",
      event: "AUDIT_FORKED",
      fields: { "Bolt slug": "u1-demo", "Source Audit Hash": "ab12cd34".repeat(8) },
    });
    expect(() => findForkAnchor(`# AI-DLC Audit Log\n${malformed}`, "u1-demo")).toThrow(
      /missing Fork Boundary/,
    );
  });
});

describe("extractPostForkDelta / countDeltaRecords", () => {
  test("extracts everything after the anchor's closing separator, verbatim", () => {
    const anchor = findForkAnchor(WT_SHARD, "u1-demo")!;
    const delta = extractPostForkDelta(WT_SHARD, anchor.forkBlock);
    expect(delta).not.toBeNull();
    expect(delta).toContain("BOLT_STARTED");
    expect(delta).toContain("BOLT_COMPLETED");
    expect(delta).not.toContain("AUDIT_FORKED");
    expect(countDeltaRecords(delta!)).toBe(2);
  });

  test("returns null when no separator closes the anchor (malformed shard)", () => {
    const truncated = WT_SHARD.slice(0, WT_SHARD.indexOf("\n---\n"));
    const anchorText = truncated.slice(truncated.indexOf("\n## Audit Forked"));
    expect(extractPostForkDelta(truncated, anchorText)).toBeNull();
  });

  test("counts zero records in a whitespace-only delta", () => {
    expect(countDeltaRecords("\n\n")).toBe(0);
  });
});

describe("auditPrefixMismatch — prefix integrity classification", () => {
  const mainBuf = Buffer.from("# AI-DLC Audit Log\nprefix-content\nlater-delta\n", "utf-8");
  const boundary = 33; // covers "# AI-DLC Audit Log\nprefix-content\n"
  const goodHash = createHash("sha256").update(mainBuf.subarray(0, boundary)).digest("hex");

  test("returns null when the prefix hash matches", () => {
    expect(auditPrefixMismatch(mainBuf, boundary, goodHash)).toBeNull();
  });

  test("classifies a too-short main shard as truncation", () => {
    const short = mainBuf.subarray(0, 10);
    const message = auditPrefixMismatch(Buffer.from(short), boundary, goodHash);
    expect(message).toMatch(/truncation suspected/);
  });

  test("classifies a same-length hash mismatch as tampering", () => {
    const tampered = Buffer.from(mainBuf);
    tampered[5] = 0x58; // flip one byte inside the hashed prefix
    const message = auditPrefixMismatch(tampered, boundary, goodHash);
    expect(message).toMatch(/tampering suspected/);
  });
});

describe("compactionPendingFromAudit — structured compaction detection", () => {
  const compacted = formatAuditRecord({
    heading: "Session Compacted",
    timestamp: "2026-07-28T12:00:00Z",
    event: "SESSION_COMPACTED",
  });
  const progress = formatAuditRecord({
    heading: "Stage Start",
    timestamp: "2026-07-28T12:01:00Z",
    event: "STAGE_STARTED",
    fields: { Stage: "code-generation" },
  });

  test("false on an empty or compaction-free buffer", () => {
    expect(compactionPendingFromAudit("")).toBe(false);
    expect(compactionPendingFromAudit(`# AI-DLC Audit Log\n${progress}`)).toBe(false);
  });

  test("true when the latest SESSION_COMPACTED has no later activity", () => {
    expect(compactionPendingFromAudit(`# AI-DLC Audit Log\n${progress}${compacted}`)).toBe(true);
  });

  test("false when stage activity follows the latest SESSION_COMPACTED", () => {
    expect(compactionPendingFromAudit(`# AI-DLC Audit Log\n${compacted}${progress}`)).toBe(false);
  });
});
